// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: acs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAcsDevice = `-- name: GetAcsDevice :one
SELECT id, tenant_id, customer_id, device_id, serial_number, manufacturer, model, wan_ip, ssid, last_inform_at, created_at, updated_at FROM acs_devices WHERE tenant_id = $1 AND device_id = $2
`

type GetAcsDeviceParams struct {
	TenantID int64  `json:"tenant_id"`
	DeviceID string `json:"device_id"`
}

func (q *Queries) GetAcsDevice(ctx context.Context, arg GetAcsDeviceParams) (AcsDevice, error) {
	row := q.db.QueryRow(ctx, getAcsDevice, arg.TenantID, arg.DeviceID)
	var i AcsDevice
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.DeviceID,
		&i.SerialNumber,
		&i.Manufacturer,
		&i.Model,
		&i.WanIp,
		&i.Ssid,
		&i.LastInformAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAcsDevices = `-- name: ListAcsDevices :many
SELECT id, tenant_id, customer_id, device_id, serial_number, manufacturer, model, wan_ip, ssid, last_inform_at, created_at, updated_at FROM acs_devices WHERE tenant_id = $1 ORDER BY updated_at DESC LIMIT $2 OFFSET $3
`

type ListAcsDevicesParams struct {
	TenantID int64 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListAcsDevices(ctx context.Context, arg ListAcsDevicesParams) ([]AcsDevice, error) {
	rows, err := q.db.Query(ctx, listAcsDevices, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AcsDevice{}
	for rows.Next() {
		var i AcsDevice
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.DeviceID,
			&i.SerialNumber,
			&i.Manufacturer,
			&i.Model,
			&i.WanIp,
			&i.Ssid,
			&i.LastInformAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAcsDevice = `-- name: UpsertAcsDevice :one
INSERT INTO acs_devices (tenant_id, customer_id, device_id, serial_number, manufacturer, model, wan_ip, ssid, last_inform_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now())
ON CONFLICT (tenant_id, device_id) DO UPDATE SET
    customer_id = EXCLUDED.customer_id, serial_number = EXCLUDED.serial_number,
    manufacturer = EXCLUDED.manufacturer, model = EXCLUDED.model, wan_ip = EXCLUDED.wan_ip,
    ssid = EXCLUDED.ssid, last_inform_at = now(), updated_at = now()
RETURNING id, tenant_id, customer_id, device_id, serial_number, manufacturer, model, wan_ip, ssid, last_inform_at, created_at, updated_at
`

type UpsertAcsDeviceParams struct {
	TenantID     int64       `json:"tenant_id"`
	CustomerID   pgtype.Int8 `json:"customer_id"`
	DeviceID     string      `json:"device_id"`
	SerialNumber string      `json:"serial_number"`
	Manufacturer string      `json:"manufacturer"`
	Model        string      `json:"model"`
	WanIp        string      `json:"wan_ip"`
	Ssid         string      `json:"ssid"`
}

func (q *Queries) UpsertAcsDevice(ctx context.Context, arg UpsertAcsDeviceParams) (AcsDevice, error) {
	row := q.db.QueryRow(ctx, upsertAcsDevice,
		arg.TenantID,
		arg.CustomerID,
		arg.DeviceID,
		arg.SerialNumber,
		arg.Manufacturer,
		arg.Model,
		arg.WanIp,
		arg.Ssid,
	)
	var i AcsDevice
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.DeviceID,
		&i.SerialNumber,
		&i.Manufacturer,
		&i.Model,
		&i.WanIp,
		&i.Ssid,
		&i.LastInformAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
