// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_logs (tenant_id, actor_user_id, action, entity, entity_id, diff, ip)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, actor_user_id, action, entity, entity_id, diff, ip, created_at
`

type InsertAuditLogParams struct {
	TenantID    int64       `json:"tenant_id"`
	ActorUserID pgtype.Int8 `json:"actor_user_id"`
	Action      string      `json:"action"`
	Entity      string      `json:"entity"`
	EntityID    string      `json:"entity_id"`
	Diff        []byte      `json:"diff"`
	Ip          pgtype.Text `json:"ip"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.TenantID,
		arg.ActorUserID,
		arg.Action,
		arg.Entity,
		arg.EntityID,
		arg.Diff,
		arg.Ip,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ActorUserID,
		&i.Action,
		&i.Entity,
		&i.EntityID,
		&i.Diff,
		&i.Ip,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, tenant_id, actor_user_id, action, entity, entity_id, diff, ip, created_at FROM audit_logs
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsParams struct {
	TenantID int64 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorUserID,
			&i.Action,
			&i.Entity,
			&i.EntityID,
			&i.Diff,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
