// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bandwidth_profiles.sql

package sqlc

import (
	"context"
)

const getBandwidthProfileByPlan = `-- name: GetBandwidthProfileByPlan :one
SELECT id, tenant_id, plan_id, rate_limit_rx, rate_limit_tx, burst_rx, burst_tx, burst_threshold_rx, burst_threshold_tx, burst_time, priority, mikrotik_rate_string, created_at, updated_at FROM bandwidth_profiles WHERE plan_id = $1
`

func (q *Queries) GetBandwidthProfileByPlan(ctx context.Context, planID int64) (BandwidthProfile, error) {
	row := q.db.QueryRow(ctx, getBandwidthProfileByPlan, planID)
	var i BandwidthProfile
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PlanID,
		&i.RateLimitRx,
		&i.RateLimitTx,
		&i.BurstRx,
		&i.BurstTx,
		&i.BurstThresholdRx,
		&i.BurstThresholdTx,
		&i.BurstTime,
		&i.Priority,
		&i.MikrotikRateString,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBandwidthProfile = `-- name: UpsertBandwidthProfile :one
INSERT INTO bandwidth_profiles (
    tenant_id, plan_id, rate_limit_rx, rate_limit_tx, burst_rx, burst_tx,
    burst_threshold_rx, burst_threshold_tx, burst_time, priority, mikrotik_rate_string
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (plan_id) DO UPDATE SET
    rate_limit_rx = EXCLUDED.rate_limit_rx,
    rate_limit_tx = EXCLUDED.rate_limit_tx,
    burst_rx = EXCLUDED.burst_rx,
    burst_tx = EXCLUDED.burst_tx,
    burst_threshold_rx = EXCLUDED.burst_threshold_rx,
    burst_threshold_tx = EXCLUDED.burst_threshold_tx,
    burst_time = EXCLUDED.burst_time,
    priority = EXCLUDED.priority,
    mikrotik_rate_string = EXCLUDED.mikrotik_rate_string,
    updated_at = now()
RETURNING id, tenant_id, plan_id, rate_limit_rx, rate_limit_tx, burst_rx, burst_tx, burst_threshold_rx, burst_threshold_tx, burst_time, priority, mikrotik_rate_string, created_at, updated_at
`

type UpsertBandwidthProfileParams struct {
	TenantID           int64  `json:"tenant_id"`
	PlanID             int64  `json:"plan_id"`
	RateLimitRx        string `json:"rate_limit_rx"`
	RateLimitTx        string `json:"rate_limit_tx"`
	BurstRx            string `json:"burst_rx"`
	BurstTx            string `json:"burst_tx"`
	BurstThresholdRx   string `json:"burst_threshold_rx"`
	BurstThresholdTx   string `json:"burst_threshold_tx"`
	BurstTime          string `json:"burst_time"`
	Priority           int32  `json:"priority"`
	MikrotikRateString string `json:"mikrotik_rate_string"`
}

func (q *Queries) UpsertBandwidthProfile(ctx context.Context, arg UpsertBandwidthProfileParams) (BandwidthProfile, error) {
	row := q.db.QueryRow(ctx, upsertBandwidthProfile,
		arg.TenantID,
		arg.PlanID,
		arg.RateLimitRx,
		arg.RateLimitTx,
		arg.BurstRx,
		arg.BurstTx,
		arg.BurstThresholdRx,
		arg.BurstThresholdTx,
		arg.BurstTime,
		arg.Priority,
		arg.MikrotikRateString,
	)
	var i BandwidthProfile
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PlanID,
		&i.RateLimitRx,
		&i.RateLimitTx,
		&i.BurstRx,
		&i.BurstTx,
		&i.BurstThresholdRx,
		&i.BurstThresholdTx,
		&i.BurstTime,
		&i.Priority,
		&i.MikrotikRateString,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
