// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (
    tenant_id, invoice_no, customer_id, period_start, period_end,
    subtotal_idr, tax_idr, discount_idr, total_idr, due_date, status, type, issued_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, now())
ON CONFLICT (customer_id, period_start) DO NOTHING
RETURNING id, tenant_id, invoice_no, customer_id, period_start, period_end, subtotal_idr, tax_idr, discount_idr, total_idr, due_date, status, type, issued_at, paid_at, created_at, updated_at
`

type CreateInvoiceParams struct {
	TenantID    int64         `json:"tenant_id"`
	InvoiceNo   string        `json:"invoice_no"`
	CustomerID  int64         `json:"customer_id"`
	PeriodStart pgtype.Date   `json:"period_start"`
	PeriodEnd   pgtype.Date   `json:"period_end"`
	SubtotalIdr int64         `json:"subtotal_idr"`
	TaxIdr      int64         `json:"tax_idr"`
	DiscountIdr int64         `json:"discount_idr"`
	TotalIdr    int64         `json:"total_idr"`
	DueDate     pgtype.Date   `json:"due_date"`
	Status      InvoiceStatus `json:"status"`
	Type        InvoiceType   `json:"type"`
}

// Idempotent per (customer, period): a conflict returns no row, which the repo
// maps to ErrInvoiceExists.
func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.TenantID,
		arg.InvoiceNo,
		arg.CustomerID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.SubtotalIdr,
		arg.TaxIdr,
		arg.DiscountIdr,
		arg.TotalIdr,
		arg.DueDate,
		arg.Status,
		arg.Type,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InvoiceNo,
		&i.CustomerID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.SubtotalIdr,
		&i.TaxIdr,
		&i.DiscountIdr,
		&i.TotalIdr,
		&i.DueDate,
		&i.Status,
		&i.Type,
		&i.IssuedAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    tenant_id, invoice_id, customer_id, amount_idr, method, gateway_provider,
    gateway_ref, status, paid_at, verified_by_user_id, idempotency_key, raw_callback
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (idempotency_key) DO NOTHING
RETURNING id, tenant_id, invoice_id, customer_id, amount_idr, method, gateway_provider, gateway_ref, status, paid_at, verified_by_user_id, idempotency_key, raw_callback, created_at
`

type CreatePaymentParams struct {
	TenantID         int64              `json:"tenant_id"`
	InvoiceID        pgtype.Int8        `json:"invoice_id"`
	CustomerID       int64              `json:"customer_id"`
	AmountIdr        int64              `json:"amount_idr"`
	Method           PaymentMethod      `json:"method"`
	GatewayProvider  string             `json:"gateway_provider"`
	GatewayRef       pgtype.Text        `json:"gateway_ref"`
	Status           PaymentStatus      `json:"status"`
	PaidAt           pgtype.Timestamptz `json:"paid_at"`
	VerifiedByUserID pgtype.Int8        `json:"verified_by_user_id"`
	IdempotencyKey   string             `json:"idempotency_key"`
	RawCallback      []byte             `json:"raw_callback"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.TenantID,
		arg.InvoiceID,
		arg.CustomerID,
		arg.AmountIdr,
		arg.Method,
		arg.GatewayProvider,
		arg.GatewayRef,
		arg.Status,
		arg.PaidAt,
		arg.VerifiedByUserID,
		arg.IdempotencyKey,
		arg.RawCallback,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InvoiceID,
		&i.CustomerID,
		&i.AmountIdr,
		&i.Method,
		&i.GatewayProvider,
		&i.GatewayRef,
		&i.Status,
		&i.PaidAt,
		&i.VerifiedByUserID,
		&i.IdempotencyKey,
		&i.RawCallback,
		&i.CreatedAt,
	)
	return i, err
}

const getInvoiceByID = `-- name: GetInvoiceByID :one
SELECT id, tenant_id, invoice_no, customer_id, period_start, period_end, subtotal_idr, tax_idr, discount_idr, total_idr, due_date, status, type, issued_at, paid_at, created_at, updated_at FROM invoices WHERE id = $1 AND tenant_id = $2
`

type GetInvoiceByIDParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) GetInvoiceByID(ctx context.Context, arg GetInvoiceByIDParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByID, arg.ID, arg.TenantID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InvoiceNo,
		&i.CustomerID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.SubtotalIdr,
		&i.TaxIdr,
		&i.DiscountIdr,
		&i.TotalIdr,
		&i.DueDate,
		&i.Status,
		&i.Type,
		&i.IssuedAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertInvoiceItem = `-- name: InsertInvoiceItem :one
INSERT INTO invoice_items (invoice_id, description, qty, unit_price_idr, amount_idr, type)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, invoice_id, description, qty, unit_price_idr, amount_idr, type
`

type InsertInvoiceItemParams struct {
	InvoiceID    int64           `json:"invoice_id"`
	Description  string          `json:"description"`
	Qty          int32           `json:"qty"`
	UnitPriceIdr int64           `json:"unit_price_idr"`
	AmountIdr    int64           `json:"amount_idr"`
	Type         InvoiceItemType `json:"type"`
}

func (q *Queries) InsertInvoiceItem(ctx context.Context, arg InsertInvoiceItemParams) (InvoiceItem, error) {
	row := q.db.QueryRow(ctx, insertInvoiceItem,
		arg.InvoiceID,
		arg.Description,
		arg.Qty,
		arg.UnitPriceIdr,
		arg.AmountIdr,
		arg.Type,
	)
	var i InvoiceItem
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.Description,
		&i.Qty,
		&i.UnitPriceIdr,
		&i.AmountIdr,
		&i.Type,
	)
	return i, err
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :one
INSERT INTO ledger_entries (tenant_id, type, category, amount_idr, ref_type, ref_id, description, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, type, category, amount_idr, ref_type, ref_id, description, created_by, created_at
`

type InsertLedgerEntryParams struct {
	TenantID    int64       `json:"tenant_id"`
	Type        LedgerType  `json:"type"`
	Category    string      `json:"category"`
	AmountIdr   int64       `json:"amount_idr"`
	RefType     string      `json:"ref_type"`
	RefID       pgtype.Int8 `json:"ref_id"`
	Description string      `json:"description"`
	CreatedBy   pgtype.Int8 `json:"created_by"`
}

func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, insertLedgerEntry,
		arg.TenantID,
		arg.Type,
		arg.Category,
		arg.AmountIdr,
		arg.RefType,
		arg.RefID,
		arg.Description,
		arg.CreatedBy,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Category,
		&i.AmountIdr,
		&i.RefType,
		&i.RefID,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listInvoiceItems = `-- name: ListInvoiceItems :many
SELECT id, invoice_id, description, qty, unit_price_idr, amount_idr, type FROM invoice_items WHERE invoice_id = $1 ORDER BY id
`

func (q *Queries) ListInvoiceItems(ctx context.Context, invoiceID int64) ([]InvoiceItem, error) {
	rows, err := q.db.Query(ctx, listInvoiceItems, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoiceItem{}
	for rows.Next() {
		var i InvoiceItem
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.Description,
			&i.Qty,
			&i.UnitPriceIdr,
			&i.AmountIdr,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesByCustomer = `-- name: ListInvoicesByCustomer :many
SELECT id, tenant_id, invoice_no, customer_id, period_start, period_end, subtotal_idr, tax_idr, discount_idr, total_idr, due_date, status, type, issued_at, paid_at, created_at, updated_at FROM invoices WHERE tenant_id = $1 AND customer_id = $2
ORDER BY period_start DESC LIMIT $3 OFFSET $4
`

type ListInvoicesByCustomerParams struct {
	TenantID   int64 `json:"tenant_id"`
	CustomerID int64 `json:"customer_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) ListInvoicesByCustomer(ctx context.Context, arg ListInvoicesByCustomerParams) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoicesByCustomer,
		arg.TenantID,
		arg.CustomerID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.InvoiceNo,
			&i.CustomerID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.SubtotalIdr,
			&i.TaxIdr,
			&i.DiscountIdr,
			&i.TotalIdr,
			&i.DueDate,
			&i.Status,
			&i.Type,
			&i.IssuedAt,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesByTenant = `-- name: ListInvoicesByTenant :many
SELECT id, tenant_id, invoice_no, customer_id, period_start, period_end, subtotal_idr, tax_idr, discount_idr, total_idr, due_date, status, type, issued_at, paid_at, created_at, updated_at FROM invoices WHERE tenant_id = $1
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListInvoicesByTenantParams struct {
	TenantID int64 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListInvoicesByTenant(ctx context.Context, arg ListInvoicesByTenantParams) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoicesByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.InvoiceNo,
			&i.CustomerID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.SubtotalIdr,
			&i.TaxIdr,
			&i.DiscountIdr,
			&i.TotalIdr,
			&i.DueDate,
			&i.Status,
			&i.Type,
			&i.IssuedAt,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByTenant = `-- name: ListPaymentsByTenant :many
SELECT id, tenant_id, invoice_id, customer_id, amount_idr, method, gateway_provider, gateway_ref, status, paid_at, verified_by_user_id, idempotency_key, raw_callback, created_at FROM payments WHERE tenant_id = $1
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListPaymentsByTenantParams struct {
	TenantID int64 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListPaymentsByTenant(ctx context.Context, arg ListPaymentsByTenantParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.InvoiceID,
			&i.CustomerID,
			&i.AmountIdr,
			&i.Method,
			&i.GatewayProvider,
			&i.GatewayRef,
			&i.Status,
			&i.PaidAt,
			&i.VerifiedByUserID,
			&i.IdempotencyKey,
			&i.RawCallback,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInvoicePaid = `-- name: MarkInvoicePaid :exec
UPDATE invoices SET status = 'paid', paid_at = now(), updated_at = now()
WHERE id = $1 AND tenant_id = $2
`

type MarkInvoicePaidParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) MarkInvoicePaid(ctx context.Context, arg MarkInvoicePaidParams) error {
	_, err := q.db.Exec(ctx, markInvoicePaid, arg.ID, arg.TenantID)
	return err
}

const markOverdueInvoices = `-- name: MarkOverdueInvoices :execrows
UPDATE invoices SET status = 'overdue', updated_at = now()
WHERE status = 'unpaid' AND due_date < CURRENT_DATE
`

func (q *Queries) MarkOverdueInvoices(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, markOverdueInvoices)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setInvoiceStatus = `-- name: SetInvoiceStatus :exec
UPDATE invoices SET status = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2
`

type SetInvoiceStatusParams struct {
	ID       int64         `json:"id"`
	TenantID int64         `json:"tenant_id"`
	Status   InvoiceStatus `json:"status"`
}

func (q *Queries) SetInvoiceStatus(ctx context.Context, arg SetInvoiceStatusParams) error {
	_, err := q.db.Exec(ctx, setInvoiceStatus, arg.ID, arg.TenantID, arg.Status)
	return err
}

const sumLedgerByType = `-- name: SumLedgerByType :many
SELECT type, COALESCE(SUM(amount_idr), 0)::BIGINT AS total
FROM ledger_entries
WHERE tenant_id = $1 AND created_at >= $2 AND created_at < $3
GROUP BY type
`

type SumLedgerByTypeParams struct {
	TenantID    int64     `json:"tenant_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

type SumLedgerByTypeRow struct {
	Type  LedgerType `json:"type"`
	Total int64      `json:"total"`
}

func (q *Queries) SumLedgerByType(ctx context.Context, arg SumLedgerByTypeParams) ([]SumLedgerByTypeRow, error) {
	rows, err := q.db.Query(ctx, sumLedgerByType, arg.TenantID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumLedgerByTypeRow{}
	for rows.Next() {
		var i SumLedgerByTypeRow
		if err := rows.Scan(&i.Type, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumOutstanding = `-- name: SumOutstanding :one
SELECT COALESCE(SUM(total_idr), 0)::BIGINT
FROM invoices
WHERE tenant_id = $1 AND status IN ('unpaid', 'overdue')
`

func (q *Queries) SumOutstanding(ctx context.Context, tenantID int64) (int64, error) {
	row := q.db.QueryRow(ctx, sumOutstanding, tenantID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
