// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCustomersByTenant = `-- name: CountCustomersByTenant :one
SELECT count(*) FROM customers WHERE tenant_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountCustomersByTenant(ctx context.Context, tenantID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomersByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (
    tenant_id, customer_no, name, id_card_no, email, phone_wa, address,
    lat, lng, install_date, status, plan_id, reseller_id, balance_idr,
    pppoe_username, pppoe_password, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
RETURNING id, tenant_id, customer_no, name, id_card_no, email, phone_wa, address, lat, lng, install_date, status, plan_id, reseller_id, balance_idr, pppoe_username, pppoe_password, notes, created_at, updated_at, deleted_at, active_until, portal_password_hash
`

type CreateCustomerParams struct {
	TenantID      int64          `json:"tenant_id"`
	CustomerNo    string         `json:"customer_no"`
	Name          string         `json:"name"`
	IDCardNo      string         `json:"id_card_no"`
	Email         string         `json:"email"`
	PhoneWa       string         `json:"phone_wa"`
	Address       string         `json:"address"`
	Lat           pgtype.Float8  `json:"lat"`
	Lng           pgtype.Float8  `json:"lng"`
	InstallDate   pgtype.Date    `json:"install_date"`
	Status        CustomerStatus `json:"status"`
	PlanID        pgtype.Int8    `json:"plan_id"`
	ResellerID    pgtype.Int8    `json:"reseller_id"`
	BalanceIdr    int64          `json:"balance_idr"`
	PppoeUsername pgtype.Text    `json:"pppoe_username"`
	PppoePassword pgtype.Text    `json:"pppoe_password"`
	Notes         string         `json:"notes"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.TenantID,
		arg.CustomerNo,
		arg.Name,
		arg.IDCardNo,
		arg.Email,
		arg.PhoneWa,
		arg.Address,
		arg.Lat,
		arg.Lng,
		arg.InstallDate,
		arg.Status,
		arg.PlanID,
		arg.ResellerID,
		arg.BalanceIdr,
		arg.PppoeUsername,
		arg.PppoePassword,
		arg.Notes,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerNo,
		&i.Name,
		&i.IDCardNo,
		&i.Email,
		&i.PhoneWa,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.InstallDate,
		&i.Status,
		&i.PlanID,
		&i.ResellerID,
		&i.BalanceIdr,
		&i.PppoeUsername,
		&i.PppoePassword,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ActiveUntil,
		&i.PortalPasswordHash,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, tenant_id, customer_no, name, id_card_no, email, phone_wa, address, lat, lng, install_date, status, plan_id, reseller_id, balance_idr, pppoe_username, pppoe_password, notes, created_at, updated_at, deleted_at, active_until, portal_password_hash FROM customers WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
`

type GetCustomerByIDParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) GetCustomerByID(ctx context.Context, arg GetCustomerByIDParams) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, arg.ID, arg.TenantID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerNo,
		&i.Name,
		&i.IDCardNo,
		&i.Email,
		&i.PhoneWa,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.InstallDate,
		&i.Status,
		&i.PlanID,
		&i.ResellerID,
		&i.BalanceIdr,
		&i.PppoeUsername,
		&i.PppoePassword,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ActiveUntil,
		&i.PortalPasswordHash,
	)
	return i, err
}

const getCustomerByNo = `-- name: GetCustomerByNo :one
SELECT id, tenant_id, customer_no, name, id_card_no, email, phone_wa, address, lat, lng, install_date, status, plan_id, reseller_id, balance_idr, pppoe_username, pppoe_password, notes, created_at, updated_at, deleted_at, active_until, portal_password_hash FROM customers WHERE tenant_id = $1 AND customer_no = $2 AND deleted_at IS NULL
`

type GetCustomerByNoParams struct {
	TenantID   int64  `json:"tenant_id"`
	CustomerNo string `json:"customer_no"`
}

func (q *Queries) GetCustomerByNo(ctx context.Context, arg GetCustomerByNoParams) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByNo, arg.TenantID, arg.CustomerNo)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerNo,
		&i.Name,
		&i.IDCardNo,
		&i.Email,
		&i.PhoneWa,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.InstallDate,
		&i.Status,
		&i.PlanID,
		&i.ResellerID,
		&i.BalanceIdr,
		&i.PppoeUsername,
		&i.PppoePassword,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ActiveUntil,
		&i.PortalPasswordHash,
	)
	return i, err
}

const listCustomersByTenant = `-- name: ListCustomersByTenant :many
SELECT id, tenant_id, customer_no, name, id_card_no, email, phone_wa, address, lat, lng, install_date, status, plan_id, reseller_id, balance_idr, pppoe_username, pppoe_password, notes, created_at, updated_at, deleted_at, active_until, portal_password_hash FROM customers
WHERE tenant_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCustomersByTenantParams struct {
	TenantID int64 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListCustomersByTenant(ctx context.Context, arg ListCustomersByTenantParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomersByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerNo,
			&i.Name,
			&i.IDCardNo,
			&i.Email,
			&i.PhoneWa,
			&i.Address,
			&i.Lat,
			&i.Lng,
			&i.InstallDate,
			&i.Status,
			&i.PlanID,
			&i.ResellerID,
			&i.BalanceIdr,
			&i.PppoeUsername,
			&i.PppoePassword,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ActiveUntil,
			&i.PortalPasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomersWithLocation = `-- name: ListCustomersWithLocation :many
SELECT id, name, lat, lng, status, customer_no FROM customers
WHERE tenant_id = $1 AND deleted_at IS NULL AND lat IS NOT NULL AND lng IS NOT NULL
`

type ListCustomersWithLocationRow struct {
	ID         int64          `json:"id"`
	Name       string         `json:"name"`
	Lat        pgtype.Float8  `json:"lat"`
	Lng        pgtype.Float8  `json:"lng"`
	Status     CustomerStatus `json:"status"`
	CustomerNo string         `json:"customer_no"`
}

func (q *Queries) ListCustomersWithLocation(ctx context.Context, tenantID int64) ([]ListCustomersWithLocationRow, error) {
	rows, err := q.db.Query(ctx, listCustomersWithLocation, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustomersWithLocationRow{}
	for rows.Next() {
		var i ListCustomersWithLocationRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Lat,
			&i.Lng,
			&i.Status,
			&i.CustomerNo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredActiveCustomers = `-- name: ListExpiredActiveCustomers :many
SELECT id, tenant_id, pppoe_username, plan_id, status
FROM customers
WHERE deleted_at IS NULL AND status = 'active'
  AND active_until IS NOT NULL AND active_until < now()
ORDER BY active_until
LIMIT $1
`

type ListExpiredActiveCustomersRow struct {
	ID            int64          `json:"id"`
	TenantID      int64          `json:"tenant_id"`
	PppoeUsername pgtype.Text    `json:"pppoe_username"`
	PlanID        pgtype.Int8    `json:"plan_id"`
	Status        CustomerStatus `json:"status"`
}

func (q *Queries) ListExpiredActiveCustomers(ctx context.Context, limit int32) ([]ListExpiredActiveCustomersRow, error) {
	rows, err := q.db.Query(ctx, listExpiredActiveCustomers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredActiveCustomersRow{}
	for rows.Next() {
		var i ListExpiredActiveCustomersRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PppoeUsername,
			&i.PlanID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCustomerActiveUntil = `-- name: SetCustomerActiveUntil :exec
UPDATE customers SET active_until = $3, status = $4, updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
`

type SetCustomerActiveUntilParams struct {
	ID          int64              `json:"id"`
	TenantID    int64              `json:"tenant_id"`
	ActiveUntil pgtype.Timestamptz `json:"active_until"`
	Status      CustomerStatus     `json:"status"`
}

func (q *Queries) SetCustomerActiveUntil(ctx context.Context, arg SetCustomerActiveUntilParams) error {
	_, err := q.db.Exec(ctx, setCustomerActiveUntil,
		arg.ID,
		arg.TenantID,
		arg.ActiveUntil,
		arg.Status,
	)
	return err
}

const setPortalPassword = `-- name: SetPortalPassword :exec
UPDATE customers SET portal_password_hash = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
`

type SetPortalPasswordParams struct {
	ID                 int64  `json:"id"`
	TenantID           int64  `json:"tenant_id"`
	PortalPasswordHash string `json:"portal_password_hash"`
}

func (q *Queries) SetPortalPassword(ctx context.Context, arg SetPortalPasswordParams) error {
	_, err := q.db.Exec(ctx, setPortalPassword, arg.ID, arg.TenantID, arg.PortalPasswordHash)
	return err
}

const softDeleteCustomer = `-- name: SoftDeleteCustomer :exec
UPDATE customers SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
`

type SoftDeleteCustomerParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) SoftDeleteCustomer(ctx context.Context, arg SoftDeleteCustomerParams) error {
	_, err := q.db.Exec(ctx, softDeleteCustomer, arg.ID, arg.TenantID)
	return err
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers SET
    name = $3, id_card_no = $4, email = $5, phone_wa = $6, address = $7,
    lat = $8, lng = $9, install_date = $10, status = $11, plan_id = $12,
    reseller_id = $13, pppoe_username = $14, pppoe_password = $15, notes = $16,
    updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
RETURNING id, tenant_id, customer_no, name, id_card_no, email, phone_wa, address, lat, lng, install_date, status, plan_id, reseller_id, balance_idr, pppoe_username, pppoe_password, notes, created_at, updated_at, deleted_at, active_until, portal_password_hash
`

type UpdateCustomerParams struct {
	ID            int64          `json:"id"`
	TenantID      int64          `json:"tenant_id"`
	Name          string         `json:"name"`
	IDCardNo      string         `json:"id_card_no"`
	Email         string         `json:"email"`
	PhoneWa       string         `json:"phone_wa"`
	Address       string         `json:"address"`
	Lat           pgtype.Float8  `json:"lat"`
	Lng           pgtype.Float8  `json:"lng"`
	InstallDate   pgtype.Date    `json:"install_date"`
	Status        CustomerStatus `json:"status"`
	PlanID        pgtype.Int8    `json:"plan_id"`
	ResellerID    pgtype.Int8    `json:"reseller_id"`
	PppoeUsername pgtype.Text    `json:"pppoe_username"`
	PppoePassword pgtype.Text    `json:"pppoe_password"`
	Notes         string         `json:"notes"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.IDCardNo,
		arg.Email,
		arg.PhoneWa,
		arg.Address,
		arg.Lat,
		arg.Lng,
		arg.InstallDate,
		arg.Status,
		arg.PlanID,
		arg.ResellerID,
		arg.PppoeUsername,
		arg.PppoePassword,
		arg.Notes,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerNo,
		&i.Name,
		&i.IDCardNo,
		&i.Email,
		&i.PhoneWa,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.InstallDate,
		&i.Status,
		&i.PlanID,
		&i.ResellerID,
		&i.BalanceIdr,
		&i.PppoeUsername,
		&i.PppoePassword,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ActiveUntil,
		&i.PortalPasswordHash,
	)
	return i, err
}

const updateCustomerStatus = `-- name: UpdateCustomerStatus :exec
UPDATE customers SET status = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
`

type UpdateCustomerStatusParams struct {
	ID       int64          `json:"id"`
	TenantID int64          `json:"tenant_id"`
	Status   CustomerStatus `json:"status"`
}

func (q *Queries) UpdateCustomerStatus(ctx context.Context, arg UpdateCustomerStatusParams) error {
	_, err := q.db.Exec(ctx, updateCustomerStatus, arg.ID, arg.TenantID, arg.Status)
	return err
}
