// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type BillingCycle string

const (
	BillingCycleMonthly      BillingCycle = "monthly"
	BillingCycleFixed        BillingCycle = "fixed"
	BillingCycleProfile      BillingCycle = "profile"
	BillingCyclePrepaidTopup BillingCycle = "prepaid_topup"
)

func (e *BillingCycle) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BillingCycle(s)
	case string:
		*e = BillingCycle(s)
	default:
		return fmt.Errorf("unsupported scan type for BillingCycle: %T", src)
	}
	return nil
}

type NullBillingCycle struct {
	BillingCycle BillingCycle `json:"billing_cycle"`
	Valid        bool         `json:"valid"` // Valid is true if BillingCycle is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBillingCycle) Scan(value interface{}) error {
	if value == nil {
		ns.BillingCycle, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BillingCycle.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBillingCycle) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BillingCycle), nil
}

type CustomerStatus string

const (
	CustomerStatusNew        CustomerStatus = "new"
	CustomerStatusActive     CustomerStatus = "active"
	CustomerStatusIsolated   CustomerStatus = "isolated"
	CustomerStatusSuspended  CustomerStatus = "suspended"
	CustomerStatusTerminated CustomerStatus = "terminated"
	CustomerStatusFree       CustomerStatus = "free"
)

func (e *CustomerStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CustomerStatus(s)
	case string:
		*e = CustomerStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CustomerStatus: %T", src)
	}
	return nil
}

type NullCustomerStatus struct {
	CustomerStatus CustomerStatus `json:"customer_status"`
	Valid          bool           `json:"valid"` // Valid is true if CustomerStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCustomerStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CustomerStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CustomerStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCustomerStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CustomerStatus), nil
}

type InvoiceItemType string

const (
	InvoiceItemTypePlan    InvoiceItemType = "plan"
	InvoiceItemTypeAddon   InvoiceItemType = "addon"
	InvoiceItemTypeInstall InvoiceItemType = "install"
	InvoiceItemTypeDevice  InvoiceItemType = "device"
)

func (e *InvoiceItemType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvoiceItemType(s)
	case string:
		*e = InvoiceItemType(s)
	default:
		return fmt.Errorf("unsupported scan type for InvoiceItemType: %T", src)
	}
	return nil
}

type NullInvoiceItemType struct {
	InvoiceItemType InvoiceItemType `json:"invoice_item_type"`
	Valid           bool            `json:"valid"` // Valid is true if InvoiceItemType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvoiceItemType) Scan(value interface{}) error {
	if value == nil {
		ns.InvoiceItemType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvoiceItemType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvoiceItemType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvoiceItemType), nil
}

type InvoiceStatus string

const (
	InvoiceStatusDraft   InvoiceStatus = "draft"
	InvoiceStatusUnpaid  InvoiceStatus = "unpaid"
	InvoiceStatusPaid    InvoiceStatus = "paid"
	InvoiceStatusOverdue InvoiceStatus = "overdue"
	InvoiceStatusVoid    InvoiceStatus = "void"
)

func (e *InvoiceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvoiceStatus(s)
	case string:
		*e = InvoiceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InvoiceStatus: %T", src)
	}
	return nil
}

type NullInvoiceStatus struct {
	InvoiceStatus InvoiceStatus `json:"invoice_status"`
	Valid         bool          `json:"valid"` // Valid is true if InvoiceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvoiceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InvoiceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvoiceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvoiceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvoiceStatus), nil
}

type InvoiceType string

const (
	InvoiceTypePrepaid  InvoiceType = "prepaid"
	InvoiceTypePostpaid InvoiceType = "postpaid"
)

func (e *InvoiceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvoiceType(s)
	case string:
		*e = InvoiceType(s)
	default:
		return fmt.Errorf("unsupported scan type for InvoiceType: %T", src)
	}
	return nil
}

type NullInvoiceType struct {
	InvoiceType InvoiceType `json:"invoice_type"`
	Valid       bool        `json:"valid"` // Valid is true if InvoiceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvoiceType) Scan(value interface{}) error {
	if value == nil {
		ns.InvoiceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvoiceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvoiceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvoiceType), nil
}

type LedgerType string

const (
	LedgerTypeIncome  LedgerType = "income"
	LedgerTypeExpense LedgerType = "expense"
)

func (e *LedgerType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LedgerType(s)
	case string:
		*e = LedgerType(s)
	default:
		return fmt.Errorf("unsupported scan type for LedgerType: %T", src)
	}
	return nil
}

type NullLedgerType struct {
	LedgerType LedgerType `json:"ledger_type"`
	Valid      bool       `json:"valid"` // Valid is true if LedgerType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLedgerType) Scan(value interface{}) error {
	if value == nil {
		ns.LedgerType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LedgerType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLedgerType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LedgerType), nil
}

type NotifChannel string

const (
	NotifChannelWa    NotifChannel = "wa"
	NotifChannelEmail NotifChannel = "email"
)

func (e *NotifChannel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotifChannel(s)
	case string:
		*e = NotifChannel(s)
	default:
		return fmt.Errorf("unsupported scan type for NotifChannel: %T", src)
	}
	return nil
}

type NullNotifChannel struct {
	NotifChannel NotifChannel `json:"notif_channel"`
	Valid        bool         `json:"valid"` // Valid is true if NotifChannel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotifChannel) Scan(value interface{}) error {
	if value == nil {
		ns.NotifChannel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotifChannel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotifChannel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotifChannel), nil
}

type NotifStatus string

const (
	NotifStatusQueued NotifStatus = "queued"
	NotifStatusSent   NotifStatus = "sent"
	NotifStatusFailed NotifStatus = "failed"
)

func (e *NotifStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotifStatus(s)
	case string:
		*e = NotifStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for NotifStatus: %T", src)
	}
	return nil
}

type NullNotifStatus struct {
	NotifStatus NotifStatus `json:"notif_status"`
	Valid       bool        `json:"valid"` // Valid is true if NotifStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotifStatus) Scan(value interface{}) error {
	if value == nil {
		ns.NotifStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotifStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotifStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotifStatus), nil
}

type PaymentMethod string

const (
	PaymentMethodCash     PaymentMethod = "cash"
	PaymentMethodTransfer PaymentMethod = "transfer"
	PaymentMethodGateway  PaymentMethod = "gateway"
	PaymentMethodBalance  PaymentMethod = "balance"
)

func (e *PaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentMethod(s)
	case string:
		*e = PaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentMethod: %T", src)
	}
	return nil
}

type NullPaymentMethod struct {
	PaymentMethod PaymentMethod `json:"payment_method"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentMethod) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentMethod), nil
}

type PaymentStatus string

const (
	PaymentStatusPending PaymentStatus = "pending"
	PaymentStatusSettled PaymentStatus = "settled"
	PaymentStatusFailed  PaymentStatus = "failed"
	PaymentStatusExpired PaymentStatus = "expired"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus `json:"payment_status"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type PgProvider string

const (
	PgProviderMidtrans PgProvider = "midtrans"
	PgProviderXendit   PgProvider = "xendit"
	PgProviderDuitku   PgProvider = "duitku"
	PgProviderTripay   PgProvider = "tripay"
)

func (e *PgProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PgProvider(s)
	case string:
		*e = PgProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for PgProvider: %T", src)
	}
	return nil
}

type NullPgProvider struct {
	PgProvider PgProvider `json:"pg_provider"`
	Valid      bool       `json:"valid"` // Valid is true if PgProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPgProvider) Scan(value interface{}) error {
	if value == nil {
		ns.PgProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PgProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPgProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PgProvider), nil
}

type ServiceType string

const (
	ServiceTypePppoe   ServiceType = "pppoe"
	ServiceTypeHotspot ServiceType = "hotspot"
	ServiceTypeDhcp    ServiceType = "dhcp"
)

func (e *ServiceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ServiceType(s)
	case string:
		*e = ServiceType(s)
	default:
		return fmt.Errorf("unsupported scan type for ServiceType: %T", src)
	}
	return nil
}

type NullServiceType struct {
	ServiceType ServiceType `json:"service_type"`
	Valid       bool        `json:"valid"` // Valid is true if ServiceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullServiceType) Scan(value interface{}) error {
	if value == nil {
		ns.ServiceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ServiceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullServiceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ServiceType), nil
}

type TenantStatus string

const (
	TenantStatusTrial     TenantStatus = "trial"
	TenantStatusActive    TenantStatus = "active"
	TenantStatusSuspended TenantStatus = "suspended"
	TenantStatusClosed    TenantStatus = "closed"
)

func (e *TenantStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TenantStatus(s)
	case string:
		*e = TenantStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TenantStatus: %T", src)
	}
	return nil
}

type NullTenantStatus struct {
	TenantStatus TenantStatus `json:"tenant_status"`
	Valid        bool         `json:"valid"` // Valid is true if TenantStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTenantStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TenantStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TenantStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTenantStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TenantStatus), nil
}

type TicketStatus string

const (
	TicketStatusOpen       TicketStatus = "open"
	TicketStatusInProgress TicketStatus = "in_progress"
	TicketStatusResolved   TicketStatus = "resolved"
	TicketStatusClosed     TicketStatus = "closed"
)

func (e *TicketStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketStatus(s)
	case string:
		*e = TicketStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketStatus: %T", src)
	}
	return nil
}

type NullTicketStatus struct {
	TicketStatus TicketStatus `json:"ticket_status"`
	Valid        bool         `json:"valid"` // Valid is true if TicketStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TicketStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketStatus), nil
}

type TicketType string

const (
	TicketTypeTrouble TicketType = "trouble"
	TicketTypeInstall TicketType = "install"
	TicketTypeOther   TicketType = "other"
)

func (e *TicketType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketType(s)
	case string:
		*e = TicketType(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketType: %T", src)
	}
	return nil
}

type NullTicketType struct {
	TicketType TicketType `json:"ticket_type"`
	Valid      bool       `json:"valid"` // Valid is true if TicketType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketType) Scan(value interface{}) error {
	if value == nil {
		ns.TicketType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketType), nil
}

type VoucherStatus string

const (
	VoucherStatusUnused   VoucherStatus = "unused"
	VoucherStatusUsed     VoucherStatus = "used"
	VoucherStatusExpired  VoucherStatus = "expired"
	VoucherStatusDisabled VoucherStatus = "disabled"
)

func (e *VoucherStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VoucherStatus(s)
	case string:
		*e = VoucherStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VoucherStatus: %T", src)
	}
	return nil
}

type NullVoucherStatus struct {
	VoucherStatus VoucherStatus `json:"voucher_status"`
	Valid         bool          `json:"valid"` // Valid is true if VoucherStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVoucherStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VoucherStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VoucherStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVoucherStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VoucherStatus), nil
}

type WaProvider string

const (
	WaProviderFonnte     WaProvider = "fonnte"
	WaProviderWablas     WaProvider = "wablas"
	WaProviderStarsender WaProvider = "starsender"
	WaProviderOnesender  WaProvider = "onesender"
	WaProviderUnofficial WaProvider = "unofficial"
)

func (e *WaProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WaProvider(s)
	case string:
		*e = WaProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for WaProvider: %T", src)
	}
	return nil
}

type NullWaProvider struct {
	WaProvider WaProvider `json:"wa_provider"`
	Valid      bool       `json:"valid"` // Valid is true if WaProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWaProvider) Scan(value interface{}) error {
	if value == nil {
		ns.WaProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WaProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWaProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WaProvider), nil
}

type AcsDevice struct {
	ID           int64              `json:"id"`
	TenantID     int64              `json:"tenant_id"`
	CustomerID   pgtype.Int8        `json:"customer_id"`
	DeviceID     string             `json:"device_id"`
	SerialNumber string             `json:"serial_number"`
	Manufacturer string             `json:"manufacturer"`
	Model        string             `json:"model"`
	WanIp        string             `json:"wan_ip"`
	Ssid         string             `json:"ssid"`
	LastInformAt pgtype.Timestamptz `json:"last_inform_at"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

type AuditLog struct {
	ID          int64       `json:"id"`
	TenantID    int64       `json:"tenant_id"`
	ActorUserID pgtype.Int8 `json:"actor_user_id"`
	Action      string      `json:"action"`
	Entity      string      `json:"entity"`
	EntityID    string      `json:"entity_id"`
	Diff        []byte      `json:"diff"`
	Ip          pgtype.Text `json:"ip"`
	CreatedAt   time.Time   `json:"created_at"`
}

type BandwidthProfile struct {
	ID                 int64     `json:"id"`
	TenantID           int64     `json:"tenant_id"`
	PlanID             int64     `json:"plan_id"`
	RateLimitRx        string    `json:"rate_limit_rx"`
	RateLimitTx        string    `json:"rate_limit_tx"`
	BurstRx            string    `json:"burst_rx"`
	BurstTx            string    `json:"burst_tx"`
	BurstThresholdRx   string    `json:"burst_threshold_rx"`
	BurstThresholdTx   string    `json:"burst_threshold_tx"`
	BurstTime          string    `json:"burst_time"`
	Priority           int32     `json:"priority"`
	MikrotikRateString string    `json:"mikrotik_rate_string"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}

type Broadcast struct {
	ID           int64     `json:"id"`
	TenantID     int64     `json:"tenant_id"`
	Segment      []byte    `json:"segment"`
	TemplateBody string    `json:"template_body"`
	Total        int32     `json:"total"`
	Sent         int32     `json:"sent"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
}

type Customer struct {
	ID                 int64              `json:"id"`
	TenantID           int64              `json:"tenant_id"`
	CustomerNo         string             `json:"customer_no"`
	Name               string             `json:"name"`
	IDCardNo           string             `json:"id_card_no"`
	Email              string             `json:"email"`
	PhoneWa            string             `json:"phone_wa"`
	Address            string             `json:"address"`
	Lat                pgtype.Float8      `json:"lat"`
	Lng                pgtype.Float8      `json:"lng"`
	InstallDate        pgtype.Date        `json:"install_date"`
	Status             CustomerStatus     `json:"status"`
	PlanID             pgtype.Int8        `json:"plan_id"`
	ResellerID         pgtype.Int8        `json:"reseller_id"`
	BalanceIdr         int64              `json:"balance_idr"`
	PppoeUsername      pgtype.Text        `json:"pppoe_username"`
	PppoePassword      pgtype.Text        `json:"pppoe_password"`
	Notes              string             `json:"notes"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	ActiveUntil        pgtype.Timestamptz `json:"active_until"`
	PortalPasswordHash string             `json:"portal_password_hash"`
}

type CustomerDocument struct {
	ID         int64     `json:"id"`
	CustomerID int64     `json:"customer_id"`
	Type       string    `json:"type"`
	FilePath   string    `json:"file_path"`
	CreatedAt  time.Time `json:"created_at"`
}

type Invoice struct {
	ID          int64              `json:"id"`
	TenantID    int64              `json:"tenant_id"`
	InvoiceNo   string             `json:"invoice_no"`
	CustomerID  int64              `json:"customer_id"`
	PeriodStart pgtype.Date        `json:"period_start"`
	PeriodEnd   pgtype.Date        `json:"period_end"`
	SubtotalIdr int64              `json:"subtotal_idr"`
	TaxIdr      int64              `json:"tax_idr"`
	DiscountIdr int64              `json:"discount_idr"`
	TotalIdr    int64              `json:"total_idr"`
	DueDate     pgtype.Date        `json:"due_date"`
	Status      InvoiceStatus      `json:"status"`
	Type        InvoiceType        `json:"type"`
	IssuedAt    pgtype.Timestamptz `json:"issued_at"`
	PaidAt      pgtype.Timestamptz `json:"paid_at"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

type InvoiceItem struct {
	ID           int64           `json:"id"`
	InvoiceID    int64           `json:"invoice_id"`
	Description  string          `json:"description"`
	Qty          int32           `json:"qty"`
	UnitPriceIdr int64           `json:"unit_price_idr"`
	AmountIdr    int64           `json:"amount_idr"`
	Type         InvoiceItemType `json:"type"`
}

type LedgerEntry struct {
	ID          int64       `json:"id"`
	TenantID    int64       `json:"tenant_id"`
	Type        LedgerType  `json:"type"`
	Category    string      `json:"category"`
	AmountIdr   int64       `json:"amount_idr"`
	RefType     string      `json:"ref_type"`
	RefID       pgtype.Int8 `json:"ref_id"`
	Description string      `json:"description"`
	CreatedBy   pgtype.Int8 `json:"created_by"`
	CreatedAt   time.Time   `json:"created_at"`
}

type MessageTemplate struct {
	ID        int64        `json:"id"`
	TenantID  int64        `json:"tenant_id"`
	Key       string       `json:"key"`
	Channel   NotifChannel `json:"channel"`
	Body      string       `json:"body"`
	IsActive  bool         `json:"is_active"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

type Na struct {
	ID          int64       `json:"id"`
	TenantID    int64       `json:"tenant_id"`
	Nasname     string      `json:"nasname"`
	Shortname   string      `json:"shortname"`
	Type        string      `json:"type"`
	Ports       pgtype.Int4 `json:"ports"`
	Secret      string      `json:"secret"`
	Server      string      `json:"server"`
	Community   string      `json:"community"`
	Description string      `json:"description"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type NotificationLog struct {
	ID            int64              `json:"id"`
	TenantID      int64              `json:"tenant_id"`
	Channel       NotifChannel       `json:"channel"`
	ToAddr        string             `json:"to_addr"`
	TemplateKey   string             `json:"template_key"`
	Payload       []byte             `json:"payload"`
	Status        NotifStatus        `json:"status"`
	ProviderRef   string             `json:"provider_ref"`
	Error         string             `json:"error"`
	Attempts      int32              `json:"attempts"`
	DedupKey      string             `json:"dedup_key"`
	NextAttemptAt time.Time          `json:"next_attempt_at"`
	CreatedAt     time.Time          `json:"created_at"`
	SentAt        pgtype.Timestamptz `json:"sent_at"`
}

type Payment struct {
	ID               int64              `json:"id"`
	TenantID         int64              `json:"tenant_id"`
	InvoiceID        pgtype.Int8        `json:"invoice_id"`
	CustomerID       int64              `json:"customer_id"`
	AmountIdr        int64              `json:"amount_idr"`
	Method           PaymentMethod      `json:"method"`
	GatewayProvider  string             `json:"gateway_provider"`
	GatewayRef       pgtype.Text        `json:"gateway_ref"`
	Status           PaymentStatus      `json:"status"`
	PaidAt           pgtype.Timestamptz `json:"paid_at"`
	VerifiedByUserID pgtype.Int8        `json:"verified_by_user_id"`
	IdempotencyKey   string             `json:"idempotency_key"`
	RawCallback      []byte             `json:"raw_callback"`
	CreatedAt        time.Time          `json:"created_at"`
}

type PaymentGateway struct {
	ID           int64      `json:"id"`
	TenantID     int64      `json:"tenant_id"`
	Provider     PgProvider `json:"provider"`
	Config       []byte     `json:"config"`
	IsActive     bool       `json:"is_active"`
	IsProduction bool       `json:"is_production"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
}

type Permission struct {
	ID          int64     `json:"id"`
	Code        string    `json:"code"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

type Plan struct {
	ID           int64              `json:"id"`
	TenantID     int64              `json:"tenant_id"`
	Name         string             `json:"name"`
	ServiceType  ServiceType        `json:"service_type"`
	PriceIdr     int64              `json:"price_idr"`
	TaxBps       int32              `json:"tax_bps"`
	BillingCycle BillingCycle       `json:"billing_cycle"`
	ActiveDays   int32              `json:"active_days"`
	DataQuotaMb  pgtype.Int8        `json:"data_quota_mb"`
	TimeQuotaSec pgtype.Int8        `json:"time_quota_sec"`
	IsUnlimited  bool               `json:"is_unlimited"`
	PoolName     string             `json:"pool_name"`
	IsolirPlanID pgtype.Int8        `json:"isolir_plan_id"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type Radacct struct {
	ID                 int64              `json:"id"`
	TenantID           int64              `json:"tenant_id"`
	Acctsessionid      string             `json:"acctsessionid"`
	Acctuniqueid       string             `json:"acctuniqueid"`
	Username           string             `json:"username"`
	Nasipaddress       string             `json:"nasipaddress"`
	Nasportid          string             `json:"nasportid"`
	Acctstarttime      time.Time          `json:"acctstarttime"`
	Acctupdatetime     pgtype.Timestamptz `json:"acctupdatetime"`
	Acctstoptime       pgtype.Timestamptz `json:"acctstoptime"`
	Acctsessiontime    int64              `json:"acctsessiontime"`
	Acctinputoctets    int64              `json:"acctinputoctets"`
	Acctoutputoctets   int64              `json:"acctoutputoctets"`
	Calledstationid    string             `json:"calledstationid"`
	Callingstationid   string             `json:"callingstationid"`
	Framedipaddress    string             `json:"framedipaddress"`
	Acctterminatecause string             `json:"acctterminatecause"`
}

type RadacctDefault struct {
	ID                 int64              `json:"id"`
	TenantID           int64              `json:"tenant_id"`
	Acctsessionid      string             `json:"acctsessionid"`
	Acctuniqueid       string             `json:"acctuniqueid"`
	Username           string             `json:"username"`
	Nasipaddress       string             `json:"nasipaddress"`
	Nasportid          string             `json:"nasportid"`
	Acctstarttime      time.Time          `json:"acctstarttime"`
	Acctupdatetime     pgtype.Timestamptz `json:"acctupdatetime"`
	Acctstoptime       pgtype.Timestamptz `json:"acctstoptime"`
	Acctsessiontime    int64              `json:"acctsessiontime"`
	Acctinputoctets    int64              `json:"acctinputoctets"`
	Acctoutputoctets   int64              `json:"acctoutputoctets"`
	Calledstationid    string             `json:"calledstationid"`
	Callingstationid   string             `json:"callingstationid"`
	Framedipaddress    string             `json:"framedipaddress"`
	Acctterminatecause string             `json:"acctterminatecause"`
}

type Radcheck struct {
	ID        int64  `json:"id"`
	TenantID  int64  `json:"tenant_id"`
	Username  string `json:"username"`
	Attribute string `json:"attribute"`
	Op        string `json:"op"`
	Value     string `json:"value"`
}

type Radgroupcheck struct {
	ID        int64  `json:"id"`
	TenantID  int64  `json:"tenant_id"`
	Groupname string `json:"groupname"`
	Attribute string `json:"attribute"`
	Op        string `json:"op"`
	Value     string `json:"value"`
}

type Radgroupreply struct {
	ID        int64  `json:"id"`
	TenantID  int64  `json:"tenant_id"`
	Groupname string `json:"groupname"`
	Attribute string `json:"attribute"`
	Op        string `json:"op"`
	Value     string `json:"value"`
}

type Radpostauth struct {
	ID           int64     `json:"id"`
	TenantID     int64     `json:"tenant_id"`
	Username     string    `json:"username"`
	Pass         string    `json:"pass"`
	Reply        string    `json:"reply"`
	Authdate     time.Time `json:"authdate"`
	Nasipaddress string    `json:"nasipaddress"`
}

type Radreply struct {
	ID        int64  `json:"id"`
	TenantID  int64  `json:"tenant_id"`
	Username  string `json:"username"`
	Attribute string `json:"attribute"`
	Op        string `json:"op"`
	Value     string `json:"value"`
}

type Radusergroup struct {
	ID        int64  `json:"id"`
	TenantID  int64  `json:"tenant_id"`
	Username  string `json:"username"`
	Groupname string `json:"groupname"`
	Priority  int32  `json:"priority"`
}

type RefreshToken struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt time.Time          `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	UserAgent string             `json:"user_agent"`
	Ip        pgtype.Text        `json:"ip"`
	CreatedAt time.Time          `json:"created_at"`
}

type Role struct {
	ID        int64     `json:"id"`
	TenantID  int64     `json:"tenant_id"`
	Name      string    `json:"name"`
	IsSystem  bool      `json:"is_system"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type RolePermission struct {
	RoleID       int64 `json:"role_id"`
	PermissionID int64 `json:"permission_id"`
}

type Tenant struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	Domain    pgtype.Text        `json:"domain"`
	Branding  []byte             `json:"branding"`
	Settings  []byte             `json:"settings"`
	Status    TenantStatus       `json:"status"`
	Plan      string             `json:"plan"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt time.Time          `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Ticket struct {
	ID             int64              `json:"id"`
	TenantID       int64              `json:"tenant_id"`
	CustomerID     pgtype.Int8        `json:"customer_id"`
	Type           TicketType         `json:"type"`
	Subject        string             `json:"subject"`
	Description    string             `json:"description"`
	Status         TicketStatus       `json:"status"`
	Priority       int32              `json:"priority"`
	AssignedUserID pgtype.Int8        `json:"assigned_user_id"`
	CreatedBy      pgtype.Int8        `json:"created_by"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
}

type TicketEvent struct {
	ID         int64       `json:"id"`
	TicketID   int64       `json:"ticket_id"`
	UserID     pgtype.Int8 `json:"user_id"`
	Note       string      `json:"note"`
	StatusFrom string      `json:"status_from"`
	StatusTo   string      `json:"status_to"`
	CreatedAt  time.Time   `json:"created_at"`
}

type User struct {
	ID           int64              `json:"id"`
	TenantID     int64              `json:"tenant_id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	RoleID       int64              `json:"role_id"`
	ParentID     pgtype.Int8        `json:"parent_id"`
	BalanceIdr   int64              `json:"balance_idr"`
	IsActive     bool               `json:"is_active"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type Voucher struct {
	ID        int64              `json:"id"`
	TenantID  int64              `json:"tenant_id"`
	BatchID   int64              `json:"batch_id"`
	Code      string             `json:"code"`
	Username  string             `json:"username"`
	Password  string             `json:"password"`
	Status    VoucherStatus      `json:"status"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	SoldAt    pgtype.Timestamptz `json:"sold_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type VoucherBatch struct {
	ID         int64       `json:"id"`
	TenantID   int64       `json:"tenant_id"`
	PlanID     int64       `json:"plan_id"`
	Prefix     string      `json:"prefix"`
	Qty        int32       `json:"qty"`
	PriceIdr   int64       `json:"price_idr"`
	TemplateID pgtype.Int8 `json:"template_id"`
	CreatedBy  pgtype.Int8 `json:"created_by"`
	CreatedAt  time.Time   `json:"created_at"`
}

type VoucherTemplate struct {
	ID        int64     `json:"id"`
	TenantID  int64     `json:"tenant_id"`
	Name      string    `json:"name"`
	Html      string    `json:"html"`
	IsDefault bool      `json:"is_default"`
	CreatedAt time.Time `json:"created_at"`
}

type WaGateway struct {
	ID         int64      `json:"id"`
	TenantID   int64      `json:"tenant_id"`
	Provider   WaProvider `json:"provider"`
	Config     []byte     `json:"config"`
	IsActive   bool       `json:"is_active"`
	DailyLimit int32      `json:"daily_limit"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
}
