// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type TenantStatus string

const (
	TenantStatusTrial     TenantStatus = "trial"
	TenantStatusActive    TenantStatus = "active"
	TenantStatusSuspended TenantStatus = "suspended"
	TenantStatusClosed    TenantStatus = "closed"
)

func (e *TenantStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TenantStatus(s)
	case string:
		*e = TenantStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TenantStatus: %T", src)
	}
	return nil
}

type NullTenantStatus struct {
	TenantStatus TenantStatus `json:"tenant_status"`
	Valid        bool         `json:"valid"` // Valid is true if TenantStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTenantStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TenantStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TenantStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTenantStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TenantStatus), nil
}

type AuditLog struct {
	ID          int64       `json:"id"`
	TenantID    int64       `json:"tenant_id"`
	ActorUserID pgtype.Int8 `json:"actor_user_id"`
	Action      string      `json:"action"`
	Entity      string      `json:"entity"`
	EntityID    string      `json:"entity_id"`
	Diff        []byte      `json:"diff"`
	Ip          pgtype.Text `json:"ip"`
	CreatedAt   time.Time   `json:"created_at"`
}

type Permission struct {
	ID          int64     `json:"id"`
	Code        string    `json:"code"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

type RefreshToken struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt time.Time          `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	UserAgent string             `json:"user_agent"`
	Ip        pgtype.Text        `json:"ip"`
	CreatedAt time.Time          `json:"created_at"`
}

type Role struct {
	ID        int64     `json:"id"`
	TenantID  int64     `json:"tenant_id"`
	Name      string    `json:"name"`
	IsSystem  bool      `json:"is_system"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type RolePermission struct {
	RoleID       int64 `json:"role_id"`
	PermissionID int64 `json:"permission_id"`
}

type Tenant struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	Domain    pgtype.Text        `json:"domain"`
	Branding  []byte             `json:"branding"`
	Settings  []byte             `json:"settings"`
	Status    TenantStatus       `json:"status"`
	Plan      string             `json:"plan"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt time.Time          `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID           int64              `json:"id"`
	TenantID     int64              `json:"tenant_id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	RoleID       int64              `json:"role_id"`
	ParentID     pgtype.Int8        `json:"parent_id"`
	BalanceIdr   int64              `json:"balance_idr"`
	IsActive     bool               `json:"is_active"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}
