// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlc

import (
	"context"
	"time"
)

const claimDueNotifications = `-- name: ClaimDueNotifications :many
UPDATE notification_logs SET next_attempt_at = $2, attempts = attempts + 1
WHERE id IN (
    SELECT id FROM notification_logs
    WHERE status = 'queued' AND next_attempt_at <= now()
    ORDER BY next_attempt_at
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, tenant_id, channel, to_addr, template_key, payload, attempts
`

type ClaimDueNotificationsParams struct {
	Limit         int32     `json:"limit"`
	NextAttemptAt time.Time `json:"next_attempt_at"`
}

type ClaimDueNotificationsRow struct {
	ID          int64        `json:"id"`
	TenantID    int64        `json:"tenant_id"`
	Channel     NotifChannel `json:"channel"`
	ToAddr      string       `json:"to_addr"`
	TemplateKey string       `json:"template_key"`
	Payload     []byte       `json:"payload"`
	Attempts    int32        `json:"attempts"`
}

// Atomically lease up to $1 due rows (bump next_attempt_at to the lease and
// increment attempts) so concurrent workers don't double-process.
func (q *Queries) ClaimDueNotifications(ctx context.Context, arg ClaimDueNotificationsParams) ([]ClaimDueNotificationsRow, error) {
	rows, err := q.db.Query(ctx, claimDueNotifications, arg.Limit, arg.NextAttemptAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimDueNotificationsRow{}
	for rows.Next() {
		var i ClaimDueNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Channel,
			&i.ToAddr,
			&i.TemplateKey,
			&i.Payload,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueNotification = `-- name: EnqueueNotification :execrows
INSERT INTO notification_logs (tenant_id, channel, to_addr, template_key, payload, dedup_key)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (dedup_key) DO NOTHING
`

type EnqueueNotificationParams struct {
	TenantID    int64        `json:"tenant_id"`
	Channel     NotifChannel `json:"channel"`
	ToAddr      string       `json:"to_addr"`
	TemplateKey string       `json:"template_key"`
	Payload     []byte       `json:"payload"`
	DedupKey    string       `json:"dedup_key"`
}

func (q *Queries) EnqueueNotification(ctx context.Context, arg EnqueueNotificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, enqueueNotification,
		arg.TenantID,
		arg.Channel,
		arg.ToAddr,
		arg.TemplateKey,
		arg.Payload,
		arg.DedupKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failNotification = `-- name: FailNotification :exec
UPDATE notification_logs SET status = 'failed', error = $2
WHERE id = $1
`

type FailNotificationParams struct {
	ID    int64  `json:"id"`
	Error string `json:"error"`
}

func (q *Queries) FailNotification(ctx context.Context, arg FailNotificationParams) error {
	_, err := q.db.Exec(ctx, failNotification, arg.ID, arg.Error)
	return err
}

const getActiveGateway = `-- name: GetActiveGateway :one
SELECT id, tenant_id, provider, config, is_active, daily_limit, created_at, updated_at FROM wa_gateways WHERE tenant_id = $1 AND is_active = true ORDER BY id LIMIT 1
`

func (q *Queries) GetActiveGateway(ctx context.Context, tenantID int64) (WaGateway, error) {
	row := q.db.QueryRow(ctx, getActiveGateway, tenantID)
	var i WaGateway
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Provider,
		&i.Config,
		&i.IsActive,
		&i.DailyLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplate = `-- name: GetTemplate :one
SELECT id, tenant_id, key, channel, body, is_active, created_at, updated_at FROM message_templates
WHERE tenant_id = $1 AND key = $2 AND channel = $3 AND is_active = true
`

type GetTemplateParams struct {
	TenantID int64        `json:"tenant_id"`
	Key      string       `json:"key"`
	Channel  NotifChannel `json:"channel"`
}

func (q *Queries) GetTemplate(ctx context.Context, arg GetTemplateParams) (MessageTemplate, error) {
	row := q.db.QueryRow(ctx, getTemplate, arg.TenantID, arg.Key, arg.Channel)
	var i MessageTemplate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Key,
		&i.Channel,
		&i.Body,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, tenant_id, channel, to_addr, template_key, payload, status, provider_ref, error, attempts, dedup_key, next_attempt_at, created_at, sent_at FROM notification_logs WHERE tenant_id = $1
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListNotificationsParams struct {
	TenantID int64 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]NotificationLog, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationLog{}
	for rows.Next() {
		var i NotificationLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Channel,
			&i.ToAddr,
			&i.TemplateKey,
			&i.Payload,
			&i.Status,
			&i.ProviderRef,
			&i.Error,
			&i.Attempts,
			&i.DedupKey,
			&i.NextAttemptAt,
			&i.CreatedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationSent = `-- name: MarkNotificationSent :exec
UPDATE notification_logs SET status = 'sent', provider_ref = $2, sent_at = now(), error = ''
WHERE id = $1
`

type MarkNotificationSentParams struct {
	ID          int64  `json:"id"`
	ProviderRef string `json:"provider_ref"`
}

func (q *Queries) MarkNotificationSent(ctx context.Context, arg MarkNotificationSentParams) error {
	_, err := q.db.Exec(ctx, markNotificationSent, arg.ID, arg.ProviderRef)
	return err
}

const retryNotification = `-- name: RetryNotification :exec
UPDATE notification_logs SET status = 'queued', error = $2, next_attempt_at = $3
WHERE id = $1
`

type RetryNotificationParams struct {
	ID            int64     `json:"id"`
	Error         string    `json:"error"`
	NextAttemptAt time.Time `json:"next_attempt_at"`
}

func (q *Queries) RetryNotification(ctx context.Context, arg RetryNotificationParams) error {
	_, err := q.db.Exec(ctx, retryNotification, arg.ID, arg.Error, arg.NextAttemptAt)
	return err
}

const upsertGateway = `-- name: UpsertGateway :one
INSERT INTO wa_gateways (tenant_id, provider, config, is_active, daily_limit)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, provider, config, is_active, daily_limit, created_at, updated_at
`

type UpsertGatewayParams struct {
	TenantID   int64      `json:"tenant_id"`
	Provider   WaProvider `json:"provider"`
	Config     []byte     `json:"config"`
	IsActive   bool       `json:"is_active"`
	DailyLimit int32      `json:"daily_limit"`
}

func (q *Queries) UpsertGateway(ctx context.Context, arg UpsertGatewayParams) (WaGateway, error) {
	row := q.db.QueryRow(ctx, upsertGateway,
		arg.TenantID,
		arg.Provider,
		arg.Config,
		arg.IsActive,
		arg.DailyLimit,
	)
	var i WaGateway
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Provider,
		&i.Config,
		&i.IsActive,
		&i.DailyLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTemplate = `-- name: UpsertTemplate :one
INSERT INTO message_templates (tenant_id, key, channel, body, is_active)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, key, channel) DO UPDATE SET body = EXCLUDED.body, is_active = EXCLUDED.is_active, updated_at = now()
RETURNING id, tenant_id, key, channel, body, is_active, created_at, updated_at
`

type UpsertTemplateParams struct {
	TenantID int64        `json:"tenant_id"`
	Key      string       `json:"key"`
	Channel  NotifChannel `json:"channel"`
	Body     string       `json:"body"`
	IsActive bool         `json:"is_active"`
}

func (q *Queries) UpsertTemplate(ctx context.Context, arg UpsertTemplateParams) (MessageTemplate, error) {
	row := q.db.QueryRow(ctx, upsertTemplate,
		arg.TenantID,
		arg.Key,
		arg.Channel,
		arg.Body,
		arg.IsActive,
	)
	var i MessageTemplate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Key,
		&i.Channel,
		&i.Body,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
