// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_gateways.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPaymentByGatewayRef = `-- name: GetPaymentByGatewayRef :one
SELECT id, tenant_id, invoice_id, customer_id, amount_idr, method, gateway_provider, gateway_ref, status, paid_at, verified_by_user_id, idempotency_key, raw_callback, created_at FROM payments WHERE gateway_ref = $1
`

func (q *Queries) GetPaymentByGatewayRef(ctx context.Context, gatewayRef pgtype.Text) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByGatewayRef, gatewayRef)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InvoiceID,
		&i.CustomerID,
		&i.AmountIdr,
		&i.Method,
		&i.GatewayProvider,
		&i.GatewayRef,
		&i.Status,
		&i.PaidAt,
		&i.VerifiedByUserID,
		&i.IdempotencyKey,
		&i.RawCallback,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentGateway = `-- name: GetPaymentGateway :one
SELECT id, tenant_id, provider, config, is_active, is_production, created_at, updated_at FROM payment_gateways
WHERE tenant_id = $1 AND provider = $2 AND is_active = true
`

type GetPaymentGatewayParams struct {
	TenantID int64      `json:"tenant_id"`
	Provider PgProvider `json:"provider"`
}

func (q *Queries) GetPaymentGateway(ctx context.Context, arg GetPaymentGatewayParams) (PaymentGateway, error) {
	row := q.db.QueryRow(ctx, getPaymentGateway, arg.TenantID, arg.Provider)
	var i PaymentGateway
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Provider,
		&i.Config,
		&i.IsActive,
		&i.IsProduction,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingGatewayPayments = `-- name: ListPendingGatewayPayments :many
SELECT id, tenant_id, invoice_id, customer_id, amount_idr, method, gateway_provider, gateway_ref, status, paid_at, verified_by_user_id, idempotency_key, raw_callback, created_at FROM payments
WHERE status = 'pending' AND method = 'gateway' AND created_at < $1
ORDER BY created_at LIMIT $2
`

type ListPendingGatewayPaymentsParams struct {
	CreatedAt time.Time `json:"created_at"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListPendingGatewayPayments(ctx context.Context, arg ListPendingGatewayPaymentsParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPendingGatewayPayments, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.InvoiceID,
			&i.CustomerID,
			&i.AmountIdr,
			&i.Method,
			&i.GatewayProvider,
			&i.GatewayRef,
			&i.Status,
			&i.PaidAt,
			&i.VerifiedByUserID,
			&i.IdempotencyKey,
			&i.RawCallback,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentStatus = `-- name: MarkPaymentStatus :exec
UPDATE payments SET status = $2, raw_callback = $3 WHERE id = $1
`

type MarkPaymentStatusParams struct {
	ID          int64         `json:"id"`
	Status      PaymentStatus `json:"status"`
	RawCallback []byte        `json:"raw_callback"`
}

func (q *Queries) MarkPaymentStatus(ctx context.Context, arg MarkPaymentStatusParams) error {
	_, err := q.db.Exec(ctx, markPaymentStatus, arg.ID, arg.Status, arg.RawCallback)
	return err
}

const settlePayment = `-- name: SettlePayment :exec
UPDATE payments SET status = 'settled', paid_at = now(), raw_callback = $2
WHERE id = $1 AND status <> 'settled'
`

type SettlePaymentParams struct {
	ID          int64  `json:"id"`
	RawCallback []byte `json:"raw_callback"`
}

func (q *Queries) SettlePayment(ctx context.Context, arg SettlePaymentParams) error {
	_, err := q.db.Exec(ctx, settlePayment, arg.ID, arg.RawCallback)
	return err
}

const upsertPaymentGateway = `-- name: UpsertPaymentGateway :one
INSERT INTO payment_gateways (tenant_id, provider, config, is_active, is_production)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, provider) DO UPDATE SET
    config = EXCLUDED.config, is_active = EXCLUDED.is_active,
    is_production = EXCLUDED.is_production, updated_at = now()
RETURNING id, tenant_id, provider, config, is_active, is_production, created_at, updated_at
`

type UpsertPaymentGatewayParams struct {
	TenantID     int64      `json:"tenant_id"`
	Provider     PgProvider `json:"provider"`
	Config       []byte     `json:"config"`
	IsActive     bool       `json:"is_active"`
	IsProduction bool       `json:"is_production"`
}

func (q *Queries) UpsertPaymentGateway(ctx context.Context, arg UpsertPaymentGatewayParams) (PaymentGateway, error) {
	row := q.db.QueryRow(ctx, upsertPaymentGateway,
		arg.TenantID,
		arg.Provider,
		arg.Config,
		arg.IsActive,
		arg.IsProduction,
	)
	var i PaymentGateway
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Provider,
		&i.Config,
		&i.IsActive,
		&i.IsProduction,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
