// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPlansByTenant = `-- name: CountPlansByTenant :one
SELECT count(*) FROM plans WHERE tenant_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountPlansByTenant(ctx context.Context, tenantID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPlansByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (
    tenant_id, name, service_type, price_idr, tax_bps, billing_cycle,
    active_days, data_quota_mb, time_quota_sec, is_unlimited, pool_name, isolir_plan_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, tenant_id, name, service_type, price_idr, tax_bps, billing_cycle, active_days, data_quota_mb, time_quota_sec, is_unlimited, pool_name, isolir_plan_id, created_at, updated_at, deleted_at
`

type CreatePlanParams struct {
	TenantID     int64        `json:"tenant_id"`
	Name         string       `json:"name"`
	ServiceType  ServiceType  `json:"service_type"`
	PriceIdr     int64        `json:"price_idr"`
	TaxBps       int32        `json:"tax_bps"`
	BillingCycle BillingCycle `json:"billing_cycle"`
	ActiveDays   int32        `json:"active_days"`
	DataQuotaMb  pgtype.Int8  `json:"data_quota_mb"`
	TimeQuotaSec pgtype.Int8  `json:"time_quota_sec"`
	IsUnlimited  bool         `json:"is_unlimited"`
	PoolName     string       `json:"pool_name"`
	IsolirPlanID pgtype.Int8  `json:"isolir_plan_id"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.TenantID,
		arg.Name,
		arg.ServiceType,
		arg.PriceIdr,
		arg.TaxBps,
		arg.BillingCycle,
		arg.ActiveDays,
		arg.DataQuotaMb,
		arg.TimeQuotaSec,
		arg.IsUnlimited,
		arg.PoolName,
		arg.IsolirPlanID,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ServiceType,
		&i.PriceIdr,
		&i.TaxBps,
		&i.BillingCycle,
		&i.ActiveDays,
		&i.DataQuotaMb,
		&i.TimeQuotaSec,
		&i.IsUnlimited,
		&i.PoolName,
		&i.IsolirPlanID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPlanByID = `-- name: GetPlanByID :one
SELECT id, tenant_id, name, service_type, price_idr, tax_bps, billing_cycle, active_days, data_quota_mb, time_quota_sec, is_unlimited, pool_name, isolir_plan_id, created_at, updated_at, deleted_at FROM plans WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
`

type GetPlanByIDParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) GetPlanByID(ctx context.Context, arg GetPlanByIDParams) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByID, arg.ID, arg.TenantID)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ServiceType,
		&i.PriceIdr,
		&i.TaxBps,
		&i.BillingCycle,
		&i.ActiveDays,
		&i.DataQuotaMb,
		&i.TimeQuotaSec,
		&i.IsUnlimited,
		&i.PoolName,
		&i.IsolirPlanID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPlansByTenant = `-- name: ListPlansByTenant :many
SELECT id, tenant_id, name, service_type, price_idr, tax_bps, billing_cycle, active_days, data_quota_mb, time_quota_sec, is_unlimited, pool_name, isolir_plan_id, created_at, updated_at, deleted_at FROM plans
WHERE tenant_id = $1 AND deleted_at IS NULL
ORDER BY name
LIMIT $2 OFFSET $3
`

type ListPlansByTenantParams struct {
	TenantID int64 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListPlansByTenant(ctx context.Context, arg ListPlansByTenantParams) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlansByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.ServiceType,
			&i.PriceIdr,
			&i.TaxBps,
			&i.BillingCycle,
			&i.ActiveDays,
			&i.DataQuotaMb,
			&i.TimeQuotaSec,
			&i.IsUnlimited,
			&i.PoolName,
			&i.IsolirPlanID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePlan = `-- name: SoftDeletePlan :exec
UPDATE plans SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
`

type SoftDeletePlanParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) SoftDeletePlan(ctx context.Context, arg SoftDeletePlanParams) error {
	_, err := q.db.Exec(ctx, softDeletePlan, arg.ID, arg.TenantID)
	return err
}

const updatePlan = `-- name: UpdatePlan :one
UPDATE plans SET
    name = $3, service_type = $4, price_idr = $5, tax_bps = $6, billing_cycle = $7,
    active_days = $8, data_quota_mb = $9, time_quota_sec = $10, is_unlimited = $11,
    pool_name = $12, isolir_plan_id = $13, updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
RETURNING id, tenant_id, name, service_type, price_idr, tax_bps, billing_cycle, active_days, data_quota_mb, time_quota_sec, is_unlimited, pool_name, isolir_plan_id, created_at, updated_at, deleted_at
`

type UpdatePlanParams struct {
	ID           int64        `json:"id"`
	TenantID     int64        `json:"tenant_id"`
	Name         string       `json:"name"`
	ServiceType  ServiceType  `json:"service_type"`
	PriceIdr     int64        `json:"price_idr"`
	TaxBps       int32        `json:"tax_bps"`
	BillingCycle BillingCycle `json:"billing_cycle"`
	ActiveDays   int32        `json:"active_days"`
	DataQuotaMb  pgtype.Int8  `json:"data_quota_mb"`
	TimeQuotaSec pgtype.Int8  `json:"time_quota_sec"`
	IsUnlimited  bool         `json:"is_unlimited"`
	PoolName     string       `json:"pool_name"`
	IsolirPlanID pgtype.Int8  `json:"isolir_plan_id"`
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, updatePlan,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.ServiceType,
		arg.PriceIdr,
		arg.TaxBps,
		arg.BillingCycle,
		arg.ActiveDays,
		arg.DataQuotaMb,
		arg.TimeQuotaSec,
		arg.IsUnlimited,
		arg.PoolName,
		arg.IsolirPlanID,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ServiceType,
		&i.PriceIdr,
		&i.TaxBps,
		&i.BillingCycle,
		&i.ActiveDays,
		&i.DataQuotaMb,
		&i.TimeQuotaSec,
		&i.IsUnlimited,
		&i.PoolName,
		&i.IsolirPlanID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
