// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error
	AddTicketEvent(ctx context.Context, arg AddTicketEventParams) (TicketEvent, error)
	AssignTicket(ctx context.Context, arg AssignTicketParams) error
	// Atomically lease up to $1 due rows (bump next_attempt_at to the lease and
	// increment attempts) so concurrent workers don't double-process.
	ClaimDueNotifications(ctx context.Context, arg ClaimDueNotificationsParams) ([]ClaimDueNotificationsRow, error)
	CountCustomersByTenant(ctx context.Context, tenantID int64) (int64, error)
	CountPlansByTenant(ctx context.Context, tenantID int64) (int64, error)
	CountUsersByTenant(ctx context.Context, tenantID int64) (int64, error)
	CountVouchersByStatus(ctx context.Context, arg CountVouchersByStatusParams) (int64, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	// Idempotent per (customer, period): a conflict returns no row, which the repo
	// maps to ErrInvoiceExists.
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error)
	CreateNas(ctx context.Context, arg CreateNasParams) (Na, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVoucher(ctx context.Context, arg CreateVoucherParams) (Voucher, error)
	CreateVoucherBatch(ctx context.Context, arg CreateVoucherBatchParams) (VoucherBatch, error)
	DeleteExpiredRefreshTokens(ctx context.Context) (int64, error)
	// Provisioning writes for RADIUS. Sync uses delete-then-insert for idempotency.
	DeleteRadCheckByUser(ctx context.Context, arg DeleteRadCheckByUserParams) error
	DeleteRadGroupReplyByGroup(ctx context.Context, arg DeleteRadGroupReplyByGroupParams) error
	DeleteRadReplyByUser(ctx context.Context, arg DeleteRadReplyByUserParams) error
	DeleteRadUserGroupByUser(ctx context.Context, arg DeleteRadUserGroupByUserParams) error
	EnqueueNotification(ctx context.Context, arg EnqueueNotificationParams) (int64, error)
	FailNotification(ctx context.Context, arg FailNotificationParams) error
	GetActiveGateway(ctx context.Context, tenantID int64) (WaGateway, error)
	GetBandwidthProfileByPlan(ctx context.Context, planID int64) (BandwidthProfile, error)
	GetCustomerByID(ctx context.Context, arg GetCustomerByIDParams) (Customer, error)
	GetInvoiceByID(ctx context.Context, arg GetInvoiceByIDParams) (Invoice, error)
	// Read-side queries used by the radius-service auth handler.
	GetNasByIP(ctx context.Context, nasname string) (GetNasByIPRow, error)
	GetPaymentByGatewayRef(ctx context.Context, gatewayRef pgtype.Text) (Payment, error)
	GetPaymentGateway(ctx context.Context, arg GetPaymentGatewayParams) (PaymentGateway, error)
	GetPlanByID(ctx context.Context, arg GetPlanByIDParams) (Plan, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRoleByID(ctx context.Context, id int64) (Role, error)
	GetRoleByName(ctx context.Context, arg GetRoleByNameParams) (Role, error)
	GetTemplate(ctx context.Context, arg GetTemplateParams) (MessageTemplate, error)
	GetTenantByDomain(ctx context.Context, domain pgtype.Text) (Tenant, error)
	GetTenantByID(ctx context.Context, id int64) (Tenant, error)
	GetTenantBySlug(ctx context.Context, slug string) (Tenant, error)
	GetTicket(ctx context.Context, arg GetTicketParams) (Ticket, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetVoucherBatch(ctx context.Context, arg GetVoucherBatchParams) (VoucherBatch, error)
	GetVoucherByCode(ctx context.Context, arg GetVoucherByCodeParams) (Voucher, error)
	GrantAllPermissionsToRole(ctx context.Context, roleID int64) error
	InsertAcctStart(ctx context.Context, arg InsertAcctStartParams) error
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error)
	InsertInvoiceItem(ctx context.Context, arg InsertInvoiceItemParams) (InvoiceItem, error)
	InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (LedgerEntry, error)
	InsertRadCheck(ctx context.Context, arg InsertRadCheckParams) error
	InsertRadGroupReply(ctx context.Context, arg InsertRadGroupReplyParams) error
	InsertRadPostAuth(ctx context.Context, arg InsertRadPostAuthParams) error
	InsertRadReply(ctx context.Context, arg InsertRadReplyParams) error
	InsertRadUserGroup(ctx context.Context, arg InsertRadUserGroupParams) error
	ListActiveSessions(ctx context.Context, arg ListActiveSessionsParams) ([]ListActiveSessionsRow, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListCustomersByTenant(ctx context.Context, arg ListCustomersByTenantParams) ([]Customer, error)
	ListCustomersWithLocation(ctx context.Context, tenantID int64) ([]ListCustomersWithLocationRow, error)
	ListExpiredActiveCustomers(ctx context.Context, limit int32) ([]ListExpiredActiveCustomersRow, error)
	ListInvoiceItems(ctx context.Context, invoiceID int64) ([]InvoiceItem, error)
	ListInvoicesByCustomer(ctx context.Context, arg ListInvoicesByCustomerParams) ([]Invoice, error)
	ListInvoicesByTenant(ctx context.Context, arg ListInvoicesByTenantParams) ([]Invoice, error)
	ListNasByTenant(ctx context.Context, tenantID int64) ([]Na, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]NotificationLog, error)
	ListPaymentsByTenant(ctx context.Context, arg ListPaymentsByTenantParams) ([]Payment, error)
	ListPendingGatewayPayments(ctx context.Context, arg ListPendingGatewayPaymentsParams) ([]Payment, error)
	ListPermissionCodesByRole(ctx context.Context, roleID int64) ([]string, error)
	ListPermissionIDsByCodes(ctx context.Context, dollar_1 []string) ([]int64, error)
	ListPermissions(ctx context.Context) ([]Permission, error)
	ListPlansByTenant(ctx context.Context, arg ListPlansByTenantParams) ([]Plan, error)
	ListRadCheckUser(ctx context.Context, arg ListRadCheckUserParams) ([]ListRadCheckUserRow, error)
	ListRadGroupReplyForGroup(ctx context.Context, arg ListRadGroupReplyForGroupParams) ([]ListRadGroupReplyForGroupRow, error)
	ListRadReplyUser(ctx context.Context, arg ListRadReplyUserParams) ([]ListRadReplyUserRow, error)
	ListRadUserGroups(ctx context.Context, arg ListRadUserGroupsParams) ([]ListRadUserGroupsRow, error)
	ListRolesByTenant(ctx context.Context, tenantID int64) ([]Role, error)
	ListTicketEvents(ctx context.Context, ticketID int64) ([]TicketEvent, error)
	ListTickets(ctx context.Context, arg ListTicketsParams) ([]Ticket, error)
	ListUsersByTenant(ctx context.Context, arg ListUsersByTenantParams) ([]User, error)
	ListVoucherBatches(ctx context.Context, arg ListVoucherBatchesParams) ([]VoucherBatch, error)
	ListVouchersByBatch(ctx context.Context, arg ListVouchersByBatchParams) ([]Voucher, error)
	MarkInvoicePaid(ctx context.Context, arg MarkInvoicePaidParams) error
	MarkNotificationSent(ctx context.Context, arg MarkNotificationSentParams) error
	MarkOverdueInvoices(ctx context.Context) (int64, error)
	MarkPaymentStatus(ctx context.Context, arg MarkPaymentStatusParams) error
	MarkVoucherUsed(ctx context.Context, arg MarkVoucherUsedParams) error
	RetryNotification(ctx context.Context, arg RetryNotificationParams) error
	RevokeAllUserRefreshTokens(ctx context.Context, userID int64) error
	RevokeRefreshToken(ctx context.Context, tokenHash string) error
	SetCustomerActiveUntil(ctx context.Context, arg SetCustomerActiveUntilParams) error
	SetInvoiceStatus(ctx context.Context, arg SetInvoiceStatusParams) error
	SetRadUserGroup(ctx context.Context, arg SetRadUserGroupParams) error
	SettlePayment(ctx context.Context, arg SettlePaymentParams) error
	SoftDeleteCustomer(ctx context.Context, arg SoftDeleteCustomerParams) error
	SoftDeletePlan(ctx context.Context, arg SoftDeletePlanParams) error
	SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) error
	SumLedgerByType(ctx context.Context, arg SumLedgerByTypeParams) ([]SumLedgerByTypeRow, error)
	SumOutstanding(ctx context.Context, tenantID int64) (int64, error)
	UpdateAcctInterim(ctx context.Context, arg UpdateAcctInterimParams) error
	UpdateAcctStop(ctx context.Context, arg UpdateAcctStopParams) error
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error)
	UpdateCustomerStatus(ctx context.Context, arg UpdateCustomerStatusParams) error
	UpdatePlan(ctx context.Context, arg UpdatePlanParams) (Plan, error)
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error)
	UpdateTicketStatus(ctx context.Context, arg UpdateTicketStatusParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserLastLogin(ctx context.Context, id int64) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpsertBandwidthProfile(ctx context.Context, arg UpsertBandwidthProfileParams) (BandwidthProfile, error)
	UpsertGateway(ctx context.Context, arg UpsertGatewayParams) (WaGateway, error)
	UpsertPaymentGateway(ctx context.Context, arg UpsertPaymentGatewayParams) (PaymentGateway, error)
	UpsertTemplate(ctx context.Context, arg UpsertTemplateParams) (MessageTemplate, error)
}

var _ Querier = (*Queries)(nil)
