// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: radius_auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNas = `-- name: CreateNas :one
INSERT INTO nas (tenant_id, nasname, shortname, type, ports, secret, server, community, description)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, nasname, shortname, type, ports, secret, server, community, description, created_at, updated_at
`

type CreateNasParams struct {
	TenantID    int64       `json:"tenant_id"`
	Nasname     string      `json:"nasname"`
	Shortname   string      `json:"shortname"`
	Type        string      `json:"type"`
	Ports       pgtype.Int4 `json:"ports"`
	Secret      string      `json:"secret"`
	Server      string      `json:"server"`
	Community   string      `json:"community"`
	Description string      `json:"description"`
}

func (q *Queries) CreateNas(ctx context.Context, arg CreateNasParams) (Na, error) {
	row := q.db.QueryRow(ctx, createNas,
		arg.TenantID,
		arg.Nasname,
		arg.Shortname,
		arg.Type,
		arg.Ports,
		arg.Secret,
		arg.Server,
		arg.Community,
		arg.Description,
	)
	var i Na
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Nasname,
		&i.Shortname,
		&i.Type,
		&i.Ports,
		&i.Secret,
		&i.Server,
		&i.Community,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNasByIP = `-- name: GetNasByIP :one

SELECT id, tenant_id, nasname, shortname, secret FROM nas WHERE nasname = $1 LIMIT 1
`

type GetNasByIPRow struct {
	ID        int64  `json:"id"`
	TenantID  int64  `json:"tenant_id"`
	Nasname   string `json:"nasname"`
	Shortname string `json:"shortname"`
	Secret    string `json:"secret"`
}

// Read-side queries used by the radius-service auth handler.
func (q *Queries) GetNasByIP(ctx context.Context, nasname string) (GetNasByIPRow, error) {
	row := q.db.QueryRow(ctx, getNasByIP, nasname)
	var i GetNasByIPRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Nasname,
		&i.Shortname,
		&i.Secret,
	)
	return i, err
}

const insertRadPostAuth = `-- name: InsertRadPostAuth :exec
INSERT INTO radpostauth (tenant_id, username, pass, reply, nasipaddress)
VALUES ($1, $2, $3, $4, $5)
`

type InsertRadPostAuthParams struct {
	TenantID     int64  `json:"tenant_id"`
	Username     string `json:"username"`
	Pass         string `json:"pass"`
	Reply        string `json:"reply"`
	Nasipaddress string `json:"nasipaddress"`
}

func (q *Queries) InsertRadPostAuth(ctx context.Context, arg InsertRadPostAuthParams) error {
	_, err := q.db.Exec(ctx, insertRadPostAuth,
		arg.TenantID,
		arg.Username,
		arg.Pass,
		arg.Reply,
		arg.Nasipaddress,
	)
	return err
}

const listNasByTenant = `-- name: ListNasByTenant :many
SELECT id, tenant_id, nasname, shortname, type, ports, secret, server, community, description, created_at, updated_at FROM nas WHERE tenant_id = $1 ORDER BY nasname
`

func (q *Queries) ListNasByTenant(ctx context.Context, tenantID int64) ([]Na, error) {
	rows, err := q.db.Query(ctx, listNasByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Na{}
	for rows.Next() {
		var i Na
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Nasname,
			&i.Shortname,
			&i.Type,
			&i.Ports,
			&i.Secret,
			&i.Server,
			&i.Community,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRadCheckUser = `-- name: ListRadCheckUser :many
SELECT attribute, op, value FROM radcheck WHERE tenant_id = $1 AND username = $2
`

type ListRadCheckUserParams struct {
	TenantID int64  `json:"tenant_id"`
	Username string `json:"username"`
}

type ListRadCheckUserRow struct {
	Attribute string `json:"attribute"`
	Op        string `json:"op"`
	Value     string `json:"value"`
}

func (q *Queries) ListRadCheckUser(ctx context.Context, arg ListRadCheckUserParams) ([]ListRadCheckUserRow, error) {
	rows, err := q.db.Query(ctx, listRadCheckUser, arg.TenantID, arg.Username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRadCheckUserRow{}
	for rows.Next() {
		var i ListRadCheckUserRow
		if err := rows.Scan(&i.Attribute, &i.Op, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRadGroupReplyForGroup = `-- name: ListRadGroupReplyForGroup :many
SELECT attribute, op, value FROM radgroupreply WHERE tenant_id = $1 AND groupname = $2
`

type ListRadGroupReplyForGroupParams struct {
	TenantID  int64  `json:"tenant_id"`
	Groupname string `json:"groupname"`
}

type ListRadGroupReplyForGroupRow struct {
	Attribute string `json:"attribute"`
	Op        string `json:"op"`
	Value     string `json:"value"`
}

func (q *Queries) ListRadGroupReplyForGroup(ctx context.Context, arg ListRadGroupReplyForGroupParams) ([]ListRadGroupReplyForGroupRow, error) {
	rows, err := q.db.Query(ctx, listRadGroupReplyForGroup, arg.TenantID, arg.Groupname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRadGroupReplyForGroupRow{}
	for rows.Next() {
		var i ListRadGroupReplyForGroupRow
		if err := rows.Scan(&i.Attribute, &i.Op, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRadReplyUser = `-- name: ListRadReplyUser :many
SELECT attribute, op, value FROM radreply WHERE tenant_id = $1 AND username = $2
`

type ListRadReplyUserParams struct {
	TenantID int64  `json:"tenant_id"`
	Username string `json:"username"`
}

type ListRadReplyUserRow struct {
	Attribute string `json:"attribute"`
	Op        string `json:"op"`
	Value     string `json:"value"`
}

func (q *Queries) ListRadReplyUser(ctx context.Context, arg ListRadReplyUserParams) ([]ListRadReplyUserRow, error) {
	rows, err := q.db.Query(ctx, listRadReplyUser, arg.TenantID, arg.Username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRadReplyUserRow{}
	for rows.Next() {
		var i ListRadReplyUserRow
		if err := rows.Scan(&i.Attribute, &i.Op, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
