// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: radius_map.sql

package sqlc

import (
	"context"
)

const deleteRadCheckByUser = `-- name: DeleteRadCheckByUser :exec

DELETE FROM radcheck WHERE tenant_id = $1 AND username = $2
`

type DeleteRadCheckByUserParams struct {
	TenantID int64  `json:"tenant_id"`
	Username string `json:"username"`
}

// Provisioning writes for RADIUS. Sync uses delete-then-insert for idempotency.
func (q *Queries) DeleteRadCheckByUser(ctx context.Context, arg DeleteRadCheckByUserParams) error {
	_, err := q.db.Exec(ctx, deleteRadCheckByUser, arg.TenantID, arg.Username)
	return err
}

const deleteRadGroupReplyByGroup = `-- name: DeleteRadGroupReplyByGroup :exec
DELETE FROM radgroupreply WHERE tenant_id = $1 AND groupname = $2
`

type DeleteRadGroupReplyByGroupParams struct {
	TenantID  int64  `json:"tenant_id"`
	Groupname string `json:"groupname"`
}

func (q *Queries) DeleteRadGroupReplyByGroup(ctx context.Context, arg DeleteRadGroupReplyByGroupParams) error {
	_, err := q.db.Exec(ctx, deleteRadGroupReplyByGroup, arg.TenantID, arg.Groupname)
	return err
}

const deleteRadReplyByUser = `-- name: DeleteRadReplyByUser :exec
DELETE FROM radreply WHERE tenant_id = $1 AND username = $2
`

type DeleteRadReplyByUserParams struct {
	TenantID int64  `json:"tenant_id"`
	Username string `json:"username"`
}

func (q *Queries) DeleteRadReplyByUser(ctx context.Context, arg DeleteRadReplyByUserParams) error {
	_, err := q.db.Exec(ctx, deleteRadReplyByUser, arg.TenantID, arg.Username)
	return err
}

const deleteRadUserGroupByUser = `-- name: DeleteRadUserGroupByUser :exec
DELETE FROM radusergroup WHERE tenant_id = $1 AND username = $2
`

type DeleteRadUserGroupByUserParams struct {
	TenantID int64  `json:"tenant_id"`
	Username string `json:"username"`
}

func (q *Queries) DeleteRadUserGroupByUser(ctx context.Context, arg DeleteRadUserGroupByUserParams) error {
	_, err := q.db.Exec(ctx, deleteRadUserGroupByUser, arg.TenantID, arg.Username)
	return err
}

const insertRadCheck = `-- name: InsertRadCheck :exec
INSERT INTO radcheck (tenant_id, username, attribute, op, value)
VALUES ($1, $2, $3, $4, $5)
`

type InsertRadCheckParams struct {
	TenantID  int64  `json:"tenant_id"`
	Username  string `json:"username"`
	Attribute string `json:"attribute"`
	Op        string `json:"op"`
	Value     string `json:"value"`
}

func (q *Queries) InsertRadCheck(ctx context.Context, arg InsertRadCheckParams) error {
	_, err := q.db.Exec(ctx, insertRadCheck,
		arg.TenantID,
		arg.Username,
		arg.Attribute,
		arg.Op,
		arg.Value,
	)
	return err
}

const insertRadGroupReply = `-- name: InsertRadGroupReply :exec
INSERT INTO radgroupreply (tenant_id, groupname, attribute, op, value)
VALUES ($1, $2, $3, $4, $5)
`

type InsertRadGroupReplyParams struct {
	TenantID  int64  `json:"tenant_id"`
	Groupname string `json:"groupname"`
	Attribute string `json:"attribute"`
	Op        string `json:"op"`
	Value     string `json:"value"`
}

func (q *Queries) InsertRadGroupReply(ctx context.Context, arg InsertRadGroupReplyParams) error {
	_, err := q.db.Exec(ctx, insertRadGroupReply,
		arg.TenantID,
		arg.Groupname,
		arg.Attribute,
		arg.Op,
		arg.Value,
	)
	return err
}

const insertRadReply = `-- name: InsertRadReply :exec
INSERT INTO radreply (tenant_id, username, attribute, op, value)
VALUES ($1, $2, $3, $4, $5)
`

type InsertRadReplyParams struct {
	TenantID  int64  `json:"tenant_id"`
	Username  string `json:"username"`
	Attribute string `json:"attribute"`
	Op        string `json:"op"`
	Value     string `json:"value"`
}

func (q *Queries) InsertRadReply(ctx context.Context, arg InsertRadReplyParams) error {
	_, err := q.db.Exec(ctx, insertRadReply,
		arg.TenantID,
		arg.Username,
		arg.Attribute,
		arg.Op,
		arg.Value,
	)
	return err
}

const insertRadUserGroup = `-- name: InsertRadUserGroup :exec
INSERT INTO radusergroup (tenant_id, username, groupname, priority)
VALUES ($1, $2, $3, $4)
`

type InsertRadUserGroupParams struct {
	TenantID  int64  `json:"tenant_id"`
	Username  string `json:"username"`
	Groupname string `json:"groupname"`
	Priority  int32  `json:"priority"`
}

func (q *Queries) InsertRadUserGroup(ctx context.Context, arg InsertRadUserGroupParams) error {
	_, err := q.db.Exec(ctx, insertRadUserGroup,
		arg.TenantID,
		arg.Username,
		arg.Groupname,
		arg.Priority,
	)
	return err
}

const listRadUserGroups = `-- name: ListRadUserGroups :many
SELECT username, groupname, priority FROM radusergroup
WHERE tenant_id = $1 AND username = $2 ORDER BY priority
`

type ListRadUserGroupsParams struct {
	TenantID int64  `json:"tenant_id"`
	Username string `json:"username"`
}

type ListRadUserGroupsRow struct {
	Username  string `json:"username"`
	Groupname string `json:"groupname"`
	Priority  int32  `json:"priority"`
}

func (q *Queries) ListRadUserGroups(ctx context.Context, arg ListRadUserGroupsParams) ([]ListRadUserGroupsRow, error) {
	rows, err := q.db.Query(ctx, listRadUserGroups, arg.TenantID, arg.Username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRadUserGroupsRow{}
	for rows.Next() {
		var i ListRadUserGroupsRow
		if err := rows.Scan(&i.Username, &i.Groupname, &i.Priority); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRadUserGroup = `-- name: SetRadUserGroup :exec
UPDATE radusergroup SET groupname = $3, priority = $4
WHERE tenant_id = $1 AND username = $2
`

type SetRadUserGroupParams struct {
	TenantID  int64  `json:"tenant_id"`
	Username  string `json:"username"`
	Groupname string `json:"groupname"`
	Priority  int32  `json:"priority"`
}

func (q *Queries) SetRadUserGroup(ctx context.Context, arg SetRadUserGroupParams) error {
	_, err := q.db.Exec(ctx, setRadUserGroup,
		arg.TenantID,
		arg.Username,
		arg.Groupname,
		arg.Priority,
	)
	return err
}
