// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: radius_acct.sql

package sqlc

import (
	"context"
	"time"
)

const insertAcctStart = `-- name: InsertAcctStart :exec
INSERT INTO radacct (
    tenant_id, acctsessionid, acctuniqueid, username, nasipaddress, nasportid,
    acctstarttime, acctupdatetime, framedipaddress, callingstationid, calledstationid
) VALUES ($1, $2, $3, $4, $5, $6, $7, $7, $8, $9, $10)
ON CONFLICT (acctuniqueid, acctstarttime) DO NOTHING
`

type InsertAcctStartParams struct {
	TenantID         int64     `json:"tenant_id"`
	Acctsessionid    string    `json:"acctsessionid"`
	Acctuniqueid     string    `json:"acctuniqueid"`
	Username         string    `json:"username"`
	Nasipaddress     string    `json:"nasipaddress"`
	Nasportid        string    `json:"nasportid"`
	Acctstarttime    time.Time `json:"acctstarttime"`
	Framedipaddress  string    `json:"framedipaddress"`
	Callingstationid string    `json:"callingstationid"`
	Calledstationid  string    `json:"calledstationid"`
}

func (q *Queries) InsertAcctStart(ctx context.Context, arg InsertAcctStartParams) error {
	_, err := q.db.Exec(ctx, insertAcctStart,
		arg.TenantID,
		arg.Acctsessionid,
		arg.Acctuniqueid,
		arg.Username,
		arg.Nasipaddress,
		arg.Nasportid,
		arg.Acctstarttime,
		arg.Framedipaddress,
		arg.Callingstationid,
		arg.Calledstationid,
	)
	return err
}

const listActiveSessions = `-- name: ListActiveSessions :many
SELECT acctsessionid, nasipaddress, framedipaddress, callingstationid
FROM radacct
WHERE tenant_id = $1 AND username = $2 AND acctstoptime IS NULL
ORDER BY acctstarttime DESC
`

type ListActiveSessionsParams struct {
	TenantID int64  `json:"tenant_id"`
	Username string `json:"username"`
}

type ListActiveSessionsRow struct {
	Acctsessionid    string `json:"acctsessionid"`
	Nasipaddress     string `json:"nasipaddress"`
	Framedipaddress  string `json:"framedipaddress"`
	Callingstationid string `json:"callingstationid"`
}

func (q *Queries) ListActiveSessions(ctx context.Context, arg ListActiveSessionsParams) ([]ListActiveSessionsRow, error) {
	rows, err := q.db.Query(ctx, listActiveSessions, arg.TenantID, arg.Username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveSessionsRow{}
	for rows.Next() {
		var i ListActiveSessionsRow
		if err := rows.Scan(
			&i.Acctsessionid,
			&i.Nasipaddress,
			&i.Framedipaddress,
			&i.Callingstationid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAcctInterim = `-- name: UpdateAcctInterim :exec
UPDATE radacct SET
    acctsessiontime = $2, acctinputoctets = $3, acctoutputoctets = $4,
    acctupdatetime = now(), framedipaddress = COALESCE(NULLIF($5::text, ''), framedipaddress)
WHERE acctuniqueid = $1 AND acctstoptime IS NULL
`

type UpdateAcctInterimParams struct {
	Acctuniqueid     string `json:"acctuniqueid"`
	Acctsessiontime  int64  `json:"acctsessiontime"`
	Acctinputoctets  int64  `json:"acctinputoctets"`
	Acctoutputoctets int64  `json:"acctoutputoctets"`
	Column5          string `json:"column_5"`
}

func (q *Queries) UpdateAcctInterim(ctx context.Context, arg UpdateAcctInterimParams) error {
	_, err := q.db.Exec(ctx, updateAcctInterim,
		arg.Acctuniqueid,
		arg.Acctsessiontime,
		arg.Acctinputoctets,
		arg.Acctoutputoctets,
		arg.Column5,
	)
	return err
}

const updateAcctStop = `-- name: UpdateAcctStop :exec
UPDATE radacct SET
    acctstoptime = now(), acctsessiontime = $2, acctinputoctets = $3,
    acctoutputoctets = $4, acctterminatecause = $5, acctupdatetime = now()
WHERE acctuniqueid = $1 AND acctstoptime IS NULL
`

type UpdateAcctStopParams struct {
	Acctuniqueid       string `json:"acctuniqueid"`
	Acctsessiontime    int64  `json:"acctsessiontime"`
	Acctinputoctets    int64  `json:"acctinputoctets"`
	Acctoutputoctets   int64  `json:"acctoutputoctets"`
	Acctterminatecause string `json:"acctterminatecause"`
}

func (q *Queries) UpdateAcctStop(ctx context.Context, arg UpdateAcctStopParams) error {
	_, err := q.db.Exec(ctx, updateAcctStop,
		arg.Acctuniqueid,
		arg.Acctsessiontime,
		arg.Acctinputoctets,
		arg.Acctoutputoctets,
		arg.Acctterminatecause,
	)
	return err
}
