// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reseller.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserBalance = `-- name: AddUserBalance :one
UPDATE users SET balance_idr = balance_idr + $2, updated_at = now()
WHERE id = $1
RETURNING balance_idr
`

type AddUserBalanceParams struct {
	ID         int64 `json:"id"`
	BalanceIdr int64 `json:"balance_idr"`
}

func (q *Queries) AddUserBalance(ctx context.Context, arg AddUserBalanceParams) (int64, error) {
	row := q.db.QueryRow(ctx, addUserBalance, arg.ID, arg.BalanceIdr)
	var balance_idr int64
	err := row.Scan(&balance_idr)
	return balance_idr, err
}

const createCommission = `-- name: CreateCommission :one
INSERT INTO commissions (tenant_id, reseller_id, source_payment_id, amount_idr, status)
VALUES ($1, $2, $3, $4, 'settled')
RETURNING id, tenant_id, reseller_id, source_payment_id, amount_idr, status, created_at
`

type CreateCommissionParams struct {
	TenantID        int64       `json:"tenant_id"`
	ResellerID      int64       `json:"reseller_id"`
	SourcePaymentID pgtype.Int8 `json:"source_payment_id"`
	AmountIdr       int64       `json:"amount_idr"`
}

func (q *Queries) CreateCommission(ctx context.Context, arg CreateCommissionParams) (Commission, error) {
	row := q.db.QueryRow(ctx, createCommission,
		arg.TenantID,
		arg.ResellerID,
		arg.SourcePaymentID,
		arg.AmountIdr,
	)
	var i Commission
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ResellerID,
		&i.SourcePaymentID,
		&i.AmountIdr,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createDeposit = `-- name: CreateDeposit :one
INSERT INTO deposits (tenant_id, user_id, amount_idr, method, gateway_ref, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, user_id, amount_idr, method, gateway_ref, status, created_at
`

type CreateDepositParams struct {
	TenantID   int64         `json:"tenant_id"`
	UserID     int64         `json:"user_id"`
	AmountIdr  int64         `json:"amount_idr"`
	Method     PaymentMethod `json:"method"`
	GatewayRef pgtype.Text   `json:"gateway_ref"`
	Status     PaymentStatus `json:"status"`
}

func (q *Queries) CreateDeposit(ctx context.Context, arg CreateDepositParams) (Deposit, error) {
	row := q.db.QueryRow(ctx, createDeposit,
		arg.TenantID,
		arg.UserID,
		arg.AmountIdr,
		arg.Method,
		arg.GatewayRef,
		arg.Status,
	)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.AmountIdr,
		&i.Method,
		&i.GatewayRef,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listCommissions = `-- name: ListCommissions :many
SELECT id, tenant_id, reseller_id, source_payment_id, amount_idr, status, created_at FROM commissions WHERE tenant_id = $1 AND reseller_id = $2
ORDER BY created_at DESC LIMIT $3 OFFSET $4
`

type ListCommissionsParams struct {
	TenantID   int64 `json:"tenant_id"`
	ResellerID int64 `json:"reseller_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) ListCommissions(ctx context.Context, arg ListCommissionsParams) ([]Commission, error) {
	rows, err := q.db.Query(ctx, listCommissions,
		arg.TenantID,
		arg.ResellerID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Commission{}
	for rows.Next() {
		var i Commission
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ResellerID,
			&i.SourcePaymentID,
			&i.AmountIdr,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeposits = `-- name: ListDeposits :many
SELECT id, tenant_id, user_id, amount_idr, method, gateway_ref, status, created_at FROM deposits WHERE tenant_id = $1 AND user_id = $2
ORDER BY created_at DESC LIMIT $3 OFFSET $4
`

type ListDepositsParams struct {
	TenantID int64 `json:"tenant_id"`
	UserID   int64 `json:"user_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListDeposits(ctx context.Context, arg ListDepositsParams) ([]Deposit, error) {
	rows, err := q.db.Query(ctx, listDeposits,
		arg.TenantID,
		arg.UserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deposit{}
	for rows.Next() {
		var i Deposit
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.AmountIdr,
			&i.Method,
			&i.GatewayRef,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
