// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, slug, domain, branding, settings, status, plan)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, slug, domain, branding, settings, status, plan, created_at, updated_at, deleted_at
`

type CreateTenantParams struct {
	Name     string       `json:"name"`
	Slug     string       `json:"slug"`
	Domain   pgtype.Text  `json:"domain"`
	Branding []byte       `json:"branding"`
	Settings []byte       `json:"settings"`
	Status   TenantStatus `json:"status"`
	Plan     string       `json:"plan"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.Name,
		arg.Slug,
		arg.Domain,
		arg.Branding,
		arg.Settings,
		arg.Status,
		arg.Plan,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Domain,
		&i.Branding,
		&i.Settings,
		&i.Status,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTenantByDomain = `-- name: GetTenantByDomain :one
SELECT id, name, slug, domain, branding, settings, status, plan, created_at, updated_at, deleted_at FROM tenants WHERE domain = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTenantByDomain(ctx context.Context, domain pgtype.Text) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByDomain, domain)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Domain,
		&i.Branding,
		&i.Settings,
		&i.Status,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, slug, domain, branding, settings, status, plan, created_at, updated_at, deleted_at FROM tenants WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTenantByID(ctx context.Context, id int64) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Domain,
		&i.Branding,
		&i.Settings,
		&i.Status,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, name, slug, domain, branding, settings, status, plan, created_at, updated_at, deleted_at FROM tenants WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Domain,
		&i.Branding,
		&i.Settings,
		&i.Status,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants
SET name = $2, domain = $3, branding = $4, settings = $5, status = $6, plan = $7, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, slug, domain, branding, settings, status, plan, created_at, updated_at, deleted_at
`

type UpdateTenantParams struct {
	ID       int64        `json:"id"`
	Name     string       `json:"name"`
	Domain   pgtype.Text  `json:"domain"`
	Branding []byte       `json:"branding"`
	Settings []byte       `json:"settings"`
	Status   TenantStatus `json:"status"`
	Plan     string       `json:"plan"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenant,
		arg.ID,
		arg.Name,
		arg.Domain,
		arg.Branding,
		arg.Settings,
		arg.Status,
		arg.Plan,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Domain,
		&i.Branding,
		&i.Settings,
		&i.Status,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
