// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tickets.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTicketEvent = `-- name: AddTicketEvent :one
INSERT INTO ticket_events (ticket_id, user_id, note, status_from, status_to)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, ticket_id, user_id, note, status_from, status_to, created_at
`

type AddTicketEventParams struct {
	TicketID   int64       `json:"ticket_id"`
	UserID     pgtype.Int8 `json:"user_id"`
	Note       string      `json:"note"`
	StatusFrom string      `json:"status_from"`
	StatusTo   string      `json:"status_to"`
}

func (q *Queries) AddTicketEvent(ctx context.Context, arg AddTicketEventParams) (TicketEvent, error) {
	row := q.db.QueryRow(ctx, addTicketEvent,
		arg.TicketID,
		arg.UserID,
		arg.Note,
		arg.StatusFrom,
		arg.StatusTo,
	)
	var i TicketEvent
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.UserID,
		&i.Note,
		&i.StatusFrom,
		&i.StatusTo,
		&i.CreatedAt,
	)
	return i, err
}

const assignTicket = `-- name: AssignTicket :exec
UPDATE tickets SET assigned_user_id = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2
`

type AssignTicketParams struct {
	ID             int64       `json:"id"`
	TenantID       int64       `json:"tenant_id"`
	AssignedUserID pgtype.Int8 `json:"assigned_user_id"`
}

func (q *Queries) AssignTicket(ctx context.Context, arg AssignTicketParams) error {
	_, err := q.db.Exec(ctx, assignTicket, arg.ID, arg.TenantID, arg.AssignedUserID)
	return err
}

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (tenant_id, customer_id, type, subject, description, status, priority, assigned_user_id, created_by)
VALUES ($1, $2, $3, $4, $5, 'open', $6, $7, $8)
RETURNING id, tenant_id, customer_id, type, subject, description, status, priority, assigned_user_id, created_by, created_at, updated_at, resolved_at
`

type CreateTicketParams struct {
	TenantID       int64       `json:"tenant_id"`
	CustomerID     pgtype.Int8 `json:"customer_id"`
	Type           TicketType  `json:"type"`
	Subject        string      `json:"subject"`
	Description    string      `json:"description"`
	Priority       int32       `json:"priority"`
	AssignedUserID pgtype.Int8 `json:"assigned_user_id"`
	CreatedBy      pgtype.Int8 `json:"created_by"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.TenantID,
		arg.CustomerID,
		arg.Type,
		arg.Subject,
		arg.Description,
		arg.Priority,
		arg.AssignedUserID,
		arg.CreatedBy,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.Type,
		&i.Subject,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssignedUserID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getTicket = `-- name: GetTicket :one
SELECT id, tenant_id, customer_id, type, subject, description, status, priority, assigned_user_id, created_by, created_at, updated_at, resolved_at FROM tickets WHERE id = $1 AND tenant_id = $2
`

type GetTicketParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) GetTicket(ctx context.Context, arg GetTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicket, arg.ID, arg.TenantID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.Type,
		&i.Subject,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssignedUserID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const listTicketEvents = `-- name: ListTicketEvents :many
SELECT id, ticket_id, user_id, note, status_from, status_to, created_at FROM ticket_events WHERE ticket_id = $1 ORDER BY created_at
`

func (q *Queries) ListTicketEvents(ctx context.Context, ticketID int64) ([]TicketEvent, error) {
	rows, err := q.db.Query(ctx, listTicketEvents, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketEvent{}
	for rows.Next() {
		var i TicketEvent
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.UserID,
			&i.Note,
			&i.StatusFrom,
			&i.StatusTo,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTickets = `-- name: ListTickets :many
SELECT id, tenant_id, customer_id, type, subject, description, status, priority, assigned_user_id, created_by, created_at, updated_at, resolved_at FROM tickets WHERE tenant_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListTicketsParams struct {
	TenantID int64 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListTickets(ctx context.Context, arg ListTicketsParams) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTickets, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.Type,
			&i.Subject,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.AssignedUserID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByCustomer = `-- name: ListTicketsByCustomer :many
SELECT id, tenant_id, customer_id, type, subject, description, status, priority, assigned_user_id, created_by, created_at, updated_at, resolved_at FROM tickets WHERE tenant_id = $1 AND customer_id = $2
ORDER BY created_at DESC LIMIT $3 OFFSET $4
`

type ListTicketsByCustomerParams struct {
	TenantID   int64       `json:"tenant_id"`
	CustomerID pgtype.Int8 `json:"customer_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListTicketsByCustomer(ctx context.Context, arg ListTicketsByCustomerParams) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTicketsByCustomer,
		arg.TenantID,
		arg.CustomerID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.Type,
			&i.Subject,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.AssignedUserID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTicketStatus = `-- name: UpdateTicketStatus :exec
UPDATE tickets SET
    status = $3,
    resolved_at = CASE WHEN $3 = 'resolved' THEN now() ELSE resolved_at END,
    updated_at = now()
WHERE id = $1 AND tenant_id = $2
`

type UpdateTicketStatusParams struct {
	ID       int64        `json:"id"`
	TenantID int64        `json:"tenant_id"`
	Status   TicketStatus `json:"status"`
}

func (q *Queries) UpdateTicketStatus(ctx context.Context, arg UpdateTicketStatusParams) error {
	_, err := q.db.Exec(ctx, updateTicketStatus, arg.ID, arg.TenantID, arg.Status)
	return err
}
