// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsersByTenant = `-- name: CountUsersByTenant :one
SELECT count(*) FROM users WHERE tenant_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountUsersByTenant(ctx context.Context, tenantID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (tenant_id, name, email, password_hash, role_id, parent_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, name, email, password_hash, role_id, parent_id, balance_idr, is_active, last_login_at, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	TenantID     int64       `json:"tenant_id"`
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	RoleID       int64       `json:"role_id"`
	ParentID     pgtype.Int8 `json:"parent_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.TenantID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.RoleID,
		arg.ParentID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.RoleID,
		&i.ParentID,
		&i.BalanceIdr,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, name, email, password_hash, role_id, parent_id, balance_idr, is_active, last_login_at, created_at, updated_at, deleted_at FROM users WHERE tenant_id = $1 AND email = $2 AND deleted_at IS NULL
`

type GetUserByEmailParams struct {
	TenantID int64  `json:"tenant_id"`
	Email    string `json:"email"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.TenantID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.RoleID,
		&i.ParentID,
		&i.BalanceIdr,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, tenant_id, name, email, password_hash, role_id, parent_id, balance_idr, is_active, last_login_at, created_at, updated_at, deleted_at FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.RoleID,
		&i.ParentID,
		&i.BalanceIdr,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUsersByTenant = `-- name: ListUsersByTenant :many
SELECT id, tenant_id, name, email, password_hash, role_id, parent_id, balance_idr, is_active, last_login_at, created_at, updated_at, deleted_at FROM users
WHERE tenant_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUsersByTenantParams struct {
	TenantID int64 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListUsersByTenant(ctx context.Context, arg ListUsersByTenantParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Email,
			&i.PasswordHash,
			&i.RoleID,
			&i.ParentID,
			&i.BalanceIdr,
			&i.IsActive,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
`

type SoftDeleteUserParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) error {
	_, err := q.db.Exec(ctx, softDeleteUser, arg.ID, arg.TenantID)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $3, role_id = $4, is_active = $5, updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
RETURNING id, tenant_id, name, email, password_hash, role_id, parent_id, balance_idr, is_active, last_login_at, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	ID       int64  `json:"id"`
	TenantID int64  `json:"tenant_id"`
	Name     string `json:"name"`
	RoleID   int64  `json:"role_id"`
	IsActive bool   `json:"is_active"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.RoleID,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.RoleID,
		&i.ParentID,
		&i.BalanceIdr,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users SET last_login_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateUserPasswordParams struct {
	ID           int64  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
