// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vouchers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countVouchersByStatus = `-- name: CountVouchersByStatus :one
SELECT count(*) FROM vouchers WHERE tenant_id = $1 AND status = $2
`

type CountVouchersByStatusParams struct {
	TenantID int64         `json:"tenant_id"`
	Status   VoucherStatus `json:"status"`
}

func (q *Queries) CountVouchersByStatus(ctx context.Context, arg CountVouchersByStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVouchersByStatus, arg.TenantID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVoucher = `-- name: CreateVoucher :one
INSERT INTO vouchers (tenant_id, batch_id, code, username, password, status)
VALUES ($1, $2, $3, $4, $5, 'unused')
RETURNING id, tenant_id, batch_id, code, username, password, status, used_at, sold_at, created_at
`

type CreateVoucherParams struct {
	TenantID int64  `json:"tenant_id"`
	BatchID  int64  `json:"batch_id"`
	Code     string `json:"code"`
	Username string `json:"username"`
	Password string `json:"password"`
}

func (q *Queries) CreateVoucher(ctx context.Context, arg CreateVoucherParams) (Voucher, error) {
	row := q.db.QueryRow(ctx, createVoucher,
		arg.TenantID,
		arg.BatchID,
		arg.Code,
		arg.Username,
		arg.Password,
	)
	var i Voucher
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BatchID,
		&i.Code,
		&i.Username,
		&i.Password,
		&i.Status,
		&i.UsedAt,
		&i.SoldAt,
		&i.CreatedAt,
	)
	return i, err
}

const createVoucherBatch = `-- name: CreateVoucherBatch :one
INSERT INTO voucher_batches (tenant_id, plan_id, prefix, qty, price_idr, template_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, plan_id, prefix, qty, price_idr, template_id, created_by, created_at
`

type CreateVoucherBatchParams struct {
	TenantID   int64       `json:"tenant_id"`
	PlanID     int64       `json:"plan_id"`
	Prefix     string      `json:"prefix"`
	Qty        int32       `json:"qty"`
	PriceIdr   int64       `json:"price_idr"`
	TemplateID pgtype.Int8 `json:"template_id"`
	CreatedBy  pgtype.Int8 `json:"created_by"`
}

func (q *Queries) CreateVoucherBatch(ctx context.Context, arg CreateVoucherBatchParams) (VoucherBatch, error) {
	row := q.db.QueryRow(ctx, createVoucherBatch,
		arg.TenantID,
		arg.PlanID,
		arg.Prefix,
		arg.Qty,
		arg.PriceIdr,
		arg.TemplateID,
		arg.CreatedBy,
	)
	var i VoucherBatch
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PlanID,
		&i.Prefix,
		&i.Qty,
		&i.PriceIdr,
		&i.TemplateID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getVoucherBatch = `-- name: GetVoucherBatch :one
SELECT id, tenant_id, plan_id, prefix, qty, price_idr, template_id, created_by, created_at FROM voucher_batches WHERE id = $1 AND tenant_id = $2
`

type GetVoucherBatchParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) GetVoucherBatch(ctx context.Context, arg GetVoucherBatchParams) (VoucherBatch, error) {
	row := q.db.QueryRow(ctx, getVoucherBatch, arg.ID, arg.TenantID)
	var i VoucherBatch
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PlanID,
		&i.Prefix,
		&i.Qty,
		&i.PriceIdr,
		&i.TemplateID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getVoucherByCode = `-- name: GetVoucherByCode :one
SELECT id, tenant_id, batch_id, code, username, password, status, used_at, sold_at, created_at FROM vouchers WHERE tenant_id = $1 AND code = $2
`

type GetVoucherByCodeParams struct {
	TenantID int64  `json:"tenant_id"`
	Code     string `json:"code"`
}

func (q *Queries) GetVoucherByCode(ctx context.Context, arg GetVoucherByCodeParams) (Voucher, error) {
	row := q.db.QueryRow(ctx, getVoucherByCode, arg.TenantID, arg.Code)
	var i Voucher
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BatchID,
		&i.Code,
		&i.Username,
		&i.Password,
		&i.Status,
		&i.UsedAt,
		&i.SoldAt,
		&i.CreatedAt,
	)
	return i, err
}

const listVoucherBatches = `-- name: ListVoucherBatches :many
SELECT id, tenant_id, plan_id, prefix, qty, price_idr, template_id, created_by, created_at FROM voucher_batches WHERE tenant_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListVoucherBatchesParams struct {
	TenantID int64 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListVoucherBatches(ctx context.Context, arg ListVoucherBatchesParams) ([]VoucherBatch, error) {
	rows, err := q.db.Query(ctx, listVoucherBatches, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VoucherBatch{}
	for rows.Next() {
		var i VoucherBatch
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PlanID,
			&i.Prefix,
			&i.Qty,
			&i.PriceIdr,
			&i.TemplateID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVouchersByBatch = `-- name: ListVouchersByBatch :many
SELECT id, tenant_id, batch_id, code, username, password, status, used_at, sold_at, created_at FROM vouchers WHERE batch_id = $1 AND tenant_id = $2 ORDER BY id LIMIT $3 OFFSET $4
`

type ListVouchersByBatchParams struct {
	BatchID  int64 `json:"batch_id"`
	TenantID int64 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListVouchersByBatch(ctx context.Context, arg ListVouchersByBatchParams) ([]Voucher, error) {
	rows, err := q.db.Query(ctx, listVouchersByBatch,
		arg.BatchID,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Voucher{}
	for rows.Next() {
		var i Voucher
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BatchID,
			&i.Code,
			&i.Username,
			&i.Password,
			&i.Status,
			&i.UsedAt,
			&i.SoldAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markVoucherUsed = `-- name: MarkVoucherUsed :exec
UPDATE vouchers SET status = 'used', used_at = now()
WHERE tenant_id = $1 AND code = $2 AND status = 'unused'
`

type MarkVoucherUsedParams struct {
	TenantID int64  `json:"tenant_id"`
	Code     string `json:"code"`
}

func (q *Queries) MarkVoucherUsed(ctx context.Context, arg MarkVoucherUsedParams) error {
	_, err := q.db.Exec(ctx, markVoucherUsed, arg.TenantID, arg.Code)
	return err
}
